#pragma once
#include <q-tee/common/common.h>

// used: [stl] size_t
#include <cstddef>
// used: [stl] uint8_t, uint16_t, uint32_t, uint64_t
#include <cstdint>

// version of the SMBIOS specification
#define Q_SMBIOS_SPECIFICATION_MAJOR 3
#define Q_SMBIOS_SPECIFICATION_MINOR 8
#define Q_SMBIOS_SPECIFICATION_PATCH 0

// version of the MCTP specification
#define Q_SMBIOS_MCTP_SPECIFICATION_MAJOR 1
#define Q_SMBIOS_MCTP_SPECIFICATION_MINOR 11
#define Q_SMBIOS_MCTP_SPECIFICATION_PATCH 0

// version of the Redfish specification
#define Q_SMBIOS_REDFISH_SPECIFICATION_MAJOR 1
#define Q_SMBIOS_REDFISH_SPECIFICATION_MINOR 3
#define Q_SMBIOS_REDFISH_SPECIFICATION_PATCH 0

/*
 * SYSTEM MANAGEMENT BIOS
 * based on DMTF-DSP0134 specification
 * @credits: https://www.dmtf.org/standards/smbios
 */
namespace SMBIOS
{
#define Q_SMBIOS_STRING_INVALID 0U
#define Q_SMBIOS_HANDLE_INVALID static_cast<std::uint16_t>(0xFFFF)

#ifdef Q_COMPILER_MSC
#pragma warning(push)
#pragma warning(disable : 4200)
#endif
#pragma pack(push, 1)
	using StringIndex_t = std::uint8_t;

	using StructureType_t = std::uint8_t;
	enum EStructureType : std::uint8_t
	{
		TYPE_PLATFORM_FIRMWARE_INFORMATION = 0U,
		TYPE_SYSTEM_INFORMATION,
		TYPE_BASEBOARD_INFORMATION,
		TYPE_SYSTEM_ENCLOSURE,
		TYPE_PROCESSOR_INFORMATION,
		TYPE_MEMORY_CONTROLLER_INFORMATION,
		TYPE_MEMORY_MODULE_INFORMATION,
		TYPE_CACHE_INFORMATION,
		TYPE_PORT_CONNECTOR_INFORMATION,
		TYPE_SYSTEM_SLOTS,
		TYPE_ONBOARD_DEVICES_INFORMATION,
		TYPE_OEM_STRINGS,
		TYPE_SYSTEM_CONFIGURATION_OPTIONS,
		TYPE_FIRMWARE_LANGUAGE_INFORMATION,
		TYPE_GROUP_ASSOCIATIONS,
		TYPE_SYSTEM_EVENT_LOG,
		TYPE_PHYSICAL_MEMORY_ARRAY,
		TYPE_MEMORY_DEVICE,
		TYPE_MEMORY_32BIT_ERROR_INFORMATION,
		TYPE_MEMORY_ARRAY_MAPPED_ADDRESS,
		TYPE_MEMORY_DEVICE_MAPPED_ADDRESS,
		TYPE_BUILTIN_POINTING_DEVICE,
		TYPE_PORTABLE_BATTERY,
		TYPE_SYSTEM_RESET,
		TYPE_HARDWARE_SECURITY,
		TYPE_SYSTEM_POWER_CONTROLS,
		TYPE_VOLTAGE_PROBE,
		TYPE_COOLING_DEVICE,
		TYPE_TEMPERATURE_PROBE,
		TYPE_ELECTRICAL_CURRENT_PROBE,
		TYPE_OUTOFBAND_REMOTE_ACCESS,
		TYPE_BOOT_INTEGRITY_SERVICES_ENTRY_POINT,
		TYPE_SYSTEM_BOOT_INFORMATION,
		TYPE_MEMORY_64BIT_ERROR_INFORMATION,
		TYPE_MANAGEMENT_DEVICE,
		TYPE_MANAGEMENT_DEVICE_COMPONENT,
		TYPE_MANAGEMENT_DEVICE_THRESHOLD_DATA,
		TYPE_MEMORY_CHANNEL,
		TYPE_IPMI_DEVICE_INFORMATION,
		TYPE_SYSTEM_POWER_SUPPLY,
		TYPE_ADDITIONAL_INFORMATION,
		TYPE_ONBOARD_DEVICES_EXTENDED_INFORMATION,
		TYPE_MANAGEMENT_CONTROLLER_HOST_INTERFACE,
		TYPE_TPM_DEVICE,
		TYPE_PROCESSOR_ADDITIONAL_INFORMATION,
		TYPE_FIRMWARE_INVENTORY_INFORMATION,
		TYPE_STRING_PROPERTY,
		// reserved 47-125
		TYPE_INACTIVE = 126U,
		TYPE_END_OF_TABLE
		// system and OEM specific 128-256
	};
	
	struct StructureHeader_t
	{
		StructureType_t nType; // 0x0
		std::uint8_t nLength; // 0x1
		std::uint16_t uHandle; // 0x2
		std::uint8_t arrData[];
	};

	using ProbeLocation_t = std::uint8_t;
	enum EProbeLocation : std::uint8_t
	{
		PROBE_LOCATION_OTHER = 1U,
		PROBE_LOCATION_UNKNOWN,
		PROBE_LOCATION_PROCESSOR,
		PROBE_LOCATION_DISK,
		PROBE_LOCATION_PERIPHERAL_BAY,
		PROBE_LOCATION_SYSTEM_MANAGEMENT_MODULE,
		PROBE_LOCATION_MOTHERBOARD,
		PROBE_LOCATION_MEMORY_MODULE,
		PROBE_LOCATION_PROCESSOR_MODULE,
		PROBE_LOCATION_POWER_UNIT,
		PROBE_LOCATION_ADD_IN_CARD,
		PROBE_LOCATION_FRONT_PANEL_BOARD,
		PROBE_LOCATION_BACK_PANEL_BOARD,
		PROBE_LOCATION_POWER_SYSTEM_BOARD,
		PROBE_LOCATION_DRIVE_BACK_PLANE
	};

	using Status_t = std::uint8_t;
	enum EStatus : std::uint8_t
	{
		STATUS_OTHER = 1U,
		STATUS_UNKNOWN,
		STATUS_OK,
		STATUS_NON_CRITICAL,
		STATUS_CRITICAL,
		STATUS_NON_RECOVERABLE
	};

	using VoltageFlags_t = std::uint8_t;
	enum EVoltageFlags : std::uint8_t
	{
		VOLTAGE_FLAG_5V = 1U << 0U,
		VOLTAGE_FLAG_3_3V = 1U << 1U,
		VOLTAGE_FLAG_2_9V = 1U << 2U
	};

	using FirmwareCharacteristics_t = std::uint64_t;
	enum EFirmwareCharacteristics : std::uint64_t
	{
		FIRMWARE_CHARACTERISTICS_UNKNOWN = (1ULL << 2ULL),
		FIRMWARE_CHARACTERISTICS_NOT_SUPPORTED = (1ULL << 3ULL),
		FIRMWARE_CHARACTERISTICS_ISA = (1ULL << 4ULL),
		FIRMWARE_CHARACTERISTICS_MCA = (1ULL << 5ULL),
		FIRMWARE_CHARACTERISTICS_EISA = (1ULL << 6ULL),
		FIRMWARE_CHARACTERISTICS_PCI = (1ULL << 7ULL),
		FIRMWARE_CHARACTERISTICS_PCMCIA = (1ULL << 8ULL),
		FIRMWARE_CHARACTERISTICS_PNP = (1ULL << 9ULL),
		FIRMWARE_CHARACTERISTICS_APM = (1ULL << 10ULL),
		FIRMWARE_CHARACTERISTICS_UPGRADEABLE = (1ULL << 11ULL),
		FIRMWARE_CHARACTERISTICS_SHADOWING = (1ULL << 12ULL),
		FIRMWARE_CHARACTERISTICS_VLVESA = (1ULL << 13ULL),
		FIRMWARE_CHARACTERISTICS_ESCD = (1ULL << 14ULL),
		FIRMWARE_CHARACTERISTICS_BOOT_FROM_CD = (1ULL << 15ULL),
		FIRMWARE_CHARACTERISTICS_SELECTABLE_BOOT = (1ULL << 16ULL),
		FIRMWARE_CHARACTERISTICS_SOCKETED_ROM = (1ULL << 17ULL),
		FIRMWARE_CHARACTERISTICS_BOOT_FROM_PCMCIA = (1ULL << 18ULL),
		FIRMWARE_CHARACTERISTICS_EDD = (1ULL << 19ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_NEC9800_SUPPORTED = (1ULL << 20ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_TOSHIBA_SUPPORTED = (1ULL << 21ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_5_25_360KB_SUPPORTED = (1ULL << 22ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_5_25_1_2MB_SUPPORTED = (1ULL << 23ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_3_5_720KB_SUPPORTED = (1ULL << 24ULL),
		FIRMWARE_CHARACTERISTICS_FLOPPY_3_5_2_88MB_SUPPORTED = (1ULL << 25ULL),
		FIRMWARE_CHARACTERISTICS_PRINT_SCREEN_SUPPORTED = (1ULL << 26ULL),
		FIRMWARE_CHARACTERISTICS_KEYBOARD_8042_SUPPORTED = (1ULL << 27ULL),
		FIRMWARE_CHARACTERISTICS_SERIAL_SUPPORTED = (1ULL << 28ULL),
		FIRMWARE_CHARACTERISTICS_PRINTER_SUPPORTED = (1ULL << 29ULL),
		FIRMWARE_CHARACTERISTICS_CGA_MONO_VIDEO_SUPPORTED = (1ULL << 30ULL),
		FIRMWARE_CHARACTERISTICS_NEC_PC98 = (1ULL << 31ULL),
		FIRMWARE_CHARACTERISTICS_RESERVED_PLATFORM_VENDOR_MASK = (0xFFFFULL << 32ULL),
		FIRMWARE_CHARACTERISTICS_RESERVED_SYSTEM_VENDOR_MASK = (0xFFFFULL << 48ULL)
	};

	struct PlatformFirmwareInformation_t
	{
		// 2.0+
		StringIndex_t nVendor; // 0x04
		StringIndex_t nFirmwareVersion; // 0x05
		std::uint16_t uStartingAddressSegment; // 0x06
		StringIndex_t nFirmwareReleaseDate; // 0x08
		std::uint8_t nFirmwareRomSize; // 0x09
		FirmwareCharacteristics_t ullFirmwareCharacteristics; // 0x0A
		// 2.1+
		union
		{
			std::uint8_t uFirmwareCharacteristicsExtension1;
			struct
			{
				std::uint8_t bACPI : 1;
				std::uint8_t bLegacyUSB : 1;
				std::uint8_t bAGP : 1;
				std::uint8_t bBootI2O : 1;
				std::uint8_t bBootLS120 : 1;
				std::uint8_t bBootATAPIZIP : 1;
				std::uint8_t bBoot1394 : 1;
				std::uint8_t bSmartBattery : 1;
			};
		}; // 0x12
		// 2.3+
		union
		{
			std::uint8_t uFirmwareCharacteristicsExtension2;
			struct
			{
				std::uint8_t bBiosBootSpecification : 1;
				std::uint8_t bFunctionKeyInitiatedNetworkServiceBoot : 1;
				std::uint8_t bTargetedContentDistribution : 1;
				std::uint8_t bUefiSpecification : 1;
				std::uint8_t bVirtualMachine : 1;
				std::uint8_t bManufacturingModeSupported : 1;
				std::uint8_t bManufacturingModeEnabled : 1;
				std::uint8_t uReserved : 1;
			};
		}; // 0x13
		// 2.4+
		std::uint8_t uPlatformFirmwareMajorRelease; // 0x14
		std::uint8_t uPlatformFirmwareMinorRelease; // 0x15
		std::uint8_t uEmbededControllerFirmwareMajorRelease; // 0x16
		std::uint8_t uEmbededControllerFirmwareMinorRelease; // 0x17
		// 3.1+
		struct
		{
			std::uint16_t nExtendedFirmwareRomSize : 14;
			std::uint16_t nExtendedFirmwareRomSizeUnit : 2;
		}; // 0x18
	};

	using SystemWakeUpType_t = std::uint8_t;
	enum ESystemWakeUpType : std::uint8_t
	{
		SYSTEM_WAKE_UP_OTHER = 1U,
		SYSTEM_WAKE_UP_UNKNOWN,
		SYSTEM_WAKE_UP_APM_TIMER,
		SYSTEM_WAKE_UP_MODEM_RING,
		SYSTEM_WAKE_UP_LAN_REMOTE,
		SYSTEM_WAKE_UP_POWER_SWITCH,
		SYSTEM_WAKE_UP_PCI_PME,
		SYSTEM_WAKE_UP_AC_POWER_RESTORED
	};

	struct SystemInformation_t
	{
		// 2.0+
		StringIndex_t nManufacturer; // 0x04
		StringIndex_t nProduct; // 0x05
		StringIndex_t nVersion; // 0x06
		StringIndex_t nSerialNumber; // 0x07
		// 2.1+
		std::uint8_t arrUUID[16]; // 0x08
		SystemWakeUpType_t nWakeUpType; // 0x18
		// 2.4+
		StringIndex_t nSkuNumber; // 0x19
		StringIndex_t nFamily; // 0x1A
	};

	using BoardType_t = std::uint8_t;
	enum EBoardType : BoardType_t
	{
		BOARD_UNKNOWN = 1U,
		BOARD_OTHER,
		BOARD_SERVER_BLADE,
		BOARD_CONNECTIVITY_SWITCH,
		BOARD_PROCESSOR_MODULE,
		BOARD_IO_MODULE,
		BOARD_MEMORY_MODULE,
		BOARD_DAUGHTER_MODULE,
		BOARD_MOTHERBOARD,
		BOARD_PROCESSOR_MEMORY_MODULE,
		BOARD_PROCESSOR_IO_MODULE,
		BOARD_INTERCONNECT_BOARD
	};

	struct BaseboardInformation_t
	{
		// 2.0+
		StringIndex_t nManufacturer; // 0x4
		StringIndex_t nProduct; // 0x5
		StringIndex_t nVersion; // 0x6
		StringIndex_t nSerialNumber; // 0x7
		StringIndex_t nAssetTag; // 0x8
		union
		{
			std::uint8_t uFeatureFlags;
			struct
			{
				std::uint8_t bIsHostingBoard : 1;
				std::uint8_t bRequiresDaughterBoard : 1;
				std::uint8_t bIsRemovable : 1;
				std::uint8_t bIsReplaceable : 1;
				std::uint8_t bIsHotSwappable : 1;
				std::uint8_t uReserved : 3;
			};
		}; // 0x9
		StringIndex_t nLocationInChassis; // 0xA
		std::uint16_t uChassisHandle; // 0xB
		BoardType_t nBoardType; // 0xD
		std::uint8_t nContainedObjectHandleCount; // 0xE
		std::uint16_t arrContainedObjectHandles[]; // 0xF
	};

	using EnclosureChassisType_t = std::uint8_t;
	enum EEnclosureChassisType : std::uint8_t
	{
		ENCLOSURE_CHASSIS_OTHER = 1U,
		ENCLOSURE_CHASSIS_UNKNOWN,
		ENCLOSURE_CHASSIS_DESKTOP,
		ENCLOSURE_CHASSIS_LOW_PROFILE_DESKTOP,
		ENCLOSURE_CHASSIS_PIZZA_BOX,
		ENCLOSURE_CHASSIS_MINI_TOWER,
		ENCLOSURE_CHASSIS_TOWER,
		ENCLOSURE_CHASSIS_PORTABLE,
		ENCLOSURE_CHASSIS_LAPTOP,
		ENCLOSURE_CHASSIS_NOTEBOOK,
		ENCLOSURE_CHASSIS_HAND_HELD,
		ENCLOSURE_CHASSIS_DOCKING_STATION,
		ENCLOSURE_CHASSIS_AIO,
		ENCLOSURE_CHASSIS_SUB_NOTEBOOK,
		ENCLOSURE_CHASSIS_SPACE_SAVING,
		ENCLOSURE_CHASSIS_LUNCH_BOX,
		ENCLOSURE_CHASSIS_MAIN_SERVER,
		ENCLOSURE_CHASSIS_EXPANSION,
		ENCLOSURE_CHASSIS_SUB,
		ENCLOSURE_CHASSIS_BUS_EXPANSION,
		ENCLOSURE_CHASSIS_PERIPHERAL,
		ENCLOSURE_CHASSIS_RAID,
		ENCLOSURE_CHASSIS_RACK_MOUNT,
		ENCLOSURE_CHASSIS_SEALED_CASE_PC,
		ENCLOSURE_CHASSIS_MULTISYSTEM,
		ENCLOSURE_CHASSIS_COMPACT_PCI,
		ENCLOSURE_CHASSIS_ADVANCED_TCA,
		ENCLOSURE_CHASSIS_BLADE,
		ENCLOSURE_CHASSIS_BLADE_SET,
		ENCLOSURE_CHASSIS_TABLET,
		ENCLOSURE_CHASSIS_CONVERTIBLE,
		ENCLOSURE_CHASSIS_DETACHABLE,
		ENCLOSURE_CHASSIS_IOT_GATEWAY,
		ENCLOSURE_CHASSIS_EMBEDDED_PC,
		ENCLOSURE_CHASSIS_MINI_PC,
		ENCLOSURE_CHASSIS_STICK_PC
	};

	using EnclosureState_t = std::uint8_t;
	enum EEnclosureState : std::uint8_t
	{
		ENCLOSURE_STATE_OTHER = 1U,
		ENCLOSURE_STATE_UNKNOWN,
		ENCLOSURE_STATE_SAFE,
		ENCLOSURE_STATE_WARNING,
		ENCLOSURE_STATE_CRITICAL,
		ENCLOSURE_STATE_NON_RECOVERABLE

	};

	using EnclosureSecurityStatus_t = std::uint8_t;
	enum EEnclosureSecurityStatus : std::uint8_t
	{
		ENCLOSURE_SECURITY_STATUS_OTHER = 1U,
		ENCLOSURE_SECURITY_STATUS_UNKNOWN,
		ENCLOSURE_SECURITY_STATUS_NONE,
		ENCLOSURE_SECURITY_STATUS_EXTERNAL_INTERFACE_LOCKED_OUT,
		ENCLOSURE_SECURITY_STATUS_EXTERNAL_INTERFACE_ENABLED
	};

	struct EnclosureContainedElement_t
	{
		// 2.3+
		struct
		{
			std::uint8_t nType : 7;
			std::uint8_t nTypeSelect : 1;
		}; // 0x00
		std::uint8_t nMinCount; // 0x01
		std::uint8_t nMaxCount; // 0x02
	};

	struct SystemEnclosure_t
	{
		// 2.0+
		StringIndex_t nManufacturer; // 0x04
		struct
		{
			EnclosureChassisType_t nChassisType : 7;
			std::uint8_t bChassisLock : 1;
		}; // 0x05
		StringIndex_t nVersion; // 0x06
		StringIndex_t nSerialNumber; // 0x07
		StringIndex_t nAssetTagNumber; // 0x08
		// 2.1+
		EnclosureState_t nBootUpState; // 0x09
		EnclosureState_t nPowerSupplyState; // 0x0A
		EnclosureState_t nThermalState; // 0x0B
		EnclosureSecurityStatus_t nSecurityStatus; // 0x0C
		// 2.3+
		std::uint32_t uOemDefined; // 0x0D
		std::uint8_t nHeight; // 0x11
		std::uint8_t nPowerCordsNumber; // 0x12
		std::uint8_t nContainedElementCount; // 0x13
		std::uint8_t nContainedElementRecordLength; // 0x14
		EnclosureContainedElement_t arrContainedElements[]; // 0x15
		// 2.7+
		// @note: fields below require manual parsing
		//StringIndex_t nSkuNumber; // 0x15 + N*L
	};

	using ProcessorType_t = std::uint8_t;
	enum EProcessorType : std::uint8_t
	{
		PROCESSOR_OTHER = 1U,
		PROCESSOR_UNKNOWN,
		PROCESSOR_CENTRAL,
		PROCESSOR_MATH,
		PROCESSOR_DSP,
		PROCESSOR_VIDEO
	};

	using ProcessorFamily_t = std::uint8_t;
	using ProcessorFamilyExtended_t = std::uint16_t;
	enum EProcessorFamily : std::uint16_t
	{
		PROCESSOR_FAMILY_OTHER = 1U,
		PROCESSOR_FAMILY_UNKNOWN,
		PROCESSOR_FAMILY_8086,
		PROCESSOR_FAMILY_80286,
		PROCESSOR_FAMILY_I386,
		PROCESSOR_FAMILY_I486,
		PROCESSOR_FAMILY_8087,
		PROCESSOR_FAMILY_80287,
		PROCESSOR_FAMILY_80387,
		PROCESSOR_FAMILY_80487,
		PROCESSOR_FAMILY_INTEL_PENTIUM,
		PROCESSOR_FAMILY_INTEL_PENTIUM_PRO,
		PROCESSOR_FAMILY_INTEL_PENTIUM_II,
		PROCESSOR_FAMILY_INTEL_PENTIUM_MMX,
		PROCESSOR_FAMILY_INTEL_CELERON,
		PROCESSOR_FAMILY_INTEL_PENTIUM_II_XEON,
		PROCESSOR_FAMILY_INTEL_PENTIUM_III,
		PROCESSOR_FAMILY_M1,
		PROCESSOR_FAMILY_M2,
		PROCESSOR_FAMILY_INTEL_CELERON_M,
		PROCESSOR_FAMILY_INTEL_PENTIUM_4HT,
		PROCESSOR_FAMILY_INTEL,
		// reserved 23
		PROCESSOR_FAMILY_AMD_DURON = 24U,
		PROCESSOR_FAMILY_AMD_K5,
		PROCESSOR_FAMILY_AMD_K6,
		PROCESSOR_FAMILY_AMD_K6_2,
		PROCESSOR_FAMILY_AMD_K6_3,
		PROCESSOR_FAMILY_AMD_ATHLON,
		PROCESSOR_FAMILY_AMD_29000,
		PROCESSOR_FAMILY_AMD_K6_2PLUS,
		PROCESSOR_FAMILY_PPC,
		PROCESSOR_FAMILY_PPC_601,
		PROCESSOR_FAMILY_PPC_603,
		PROCESSOR_FAMILY_PPC_603PLUS,
		PROCESSOR_FAMILY_PPC_604,
		PROCESSOR_FAMILY_PPC_620,
		PROCESSOR_FAMILY_PPC_X704,
		PROCESSOR_FAMILY_PPC_750,
		PROCESSOR_FAMILY_INTEL_CORE_DUO,
		PROCESSOR_FAMILY_INTEL_CORE_DUO_MOBILE,
		PROCESSOR_FAMILY_INTEL_CORE_SOLO_MOBILE,
		PROCESSOR_FAMILY_INTEL_ATOM,
		PROCESSOR_FAMILY_INTEL_CORE_M,
		PROCESSOR_FAMILY_INTEL_CORE_M3,
		PROCESSOR_FAMILY_INTEL_CORE_M5,
		PROCESSOR_FAMILY_INTEL_CORE_M7,
		PROCESSOR_FAMILY_ALPHA,
		PROCESSOR_FAMILY_ALPHA_21064,
		PROCESSOR_FAMILY_ALPHA_21066,
		PROCESSOR_FAMILY_ALPHA_21164,
		PROCESSOR_FAMILY_ALPHA_21164PC,
		PROCESSOR_FAMILY_ALPHA_21164A,
		PROCESSOR_FAMILY_ALPHA_21264,
		PROCESSOR_FAMILY_ALPHA_21364,
		PROCESSOR_FAMILY_AMD_TURION_II_ULTRA_MOBILE_M,
		PROCESSOR_FAMILY_AMD_TURION_II_MOBILE_M,
		PROCESSOR_FAMILY_AMD_ATHLON_II_M,
		PROCESSOR_FAMILY_AMD_OPTERON_6100,
		PROCESSOR_FAMILY_AMD_OPTERON_4100,
		PROCESSOR_FAMILY_AMD_OPTERON_6200,
		PROCESSOR_FAMILY_AMD_OPTERON_4200,
		PROCESSOR_FAMILY_AMD_FX,
		PROCESSOR_FAMILY_MIPS,
		PROCESSOR_FAMILY_MIPS_R4000,
		PROCESSOR_FAMILY_MIPS_R4200,
		PROCESSOR_FAMILY_MIPS_R4400,
		PROCESSOR_FAMILY_MIPS_R4600,
		PROCESSOR_FAMILY_MIPS_R10000,
		PROCESSOR_FAMILY_AMD_C,
		PROCESSOR_FAMILY_AMD_E,
		PROCESSOR_FAMILY_AMD_A,
		PROCESSOR_FAMILY_AMD_G,
		PROCESSOR_FAMILY_AMD_Z,
		PROCESSOR_FAMILY_AMD_R,
		PROCESSOR_FAMILY_AMD_OPTERON_4300,
		PROCESSOR_FAMILY_AMD_OPTERON_6300,
		PROCESSOR_FAMILY_AMD_OPTERON_3300,
		PROCESSOR_FAMILY_AMD_FIREPRO,
		PROCESSOR_FAMILY_SPARC,
		PROCESSOR_FAMILY_SUPERSPARC,
		PROCESSOR_FAMILY_MIRCOSPARC_II,
		PROCESSOR_FAMILY_MIRCOSPARC_IIEP,
		PROCESSOR_FAMILY_ULTRASPARC,
		PROCESSOR_FAMILY_ULTRASPARC_II,
		PROCESSOR_FAMILY_ULTRASPARC_I2,
		PROCESSOR_FAMILY_ULTRASPARC_III,
		PROCESSOR_FAMILY_ULTRASPARC_III1,
		// reserved 89-95
		PROCESSOR_FAMILY_68040 = 96U,
		PROCESSOR_FAMILY_68XXX,
		PROCESSOR_FAMILY_68000,
		PROCESSOR_FAMILY_68010,
		PROCESSOR_FAMILY_68020,
		PROCESSOR_FAMILY_68030,
		PROCESSOR_FAMILY_AMD_ATHLON_X4_QUAD_CORE,
		PROCESSOR_FAMILY_AMD_OPTERON_X1000,
		PROCESSOR_FAMILY_AMD_OPTERON_X2000,
		PROCESSOR_FAMILY_AMD_OPTERON_A,
		PROCESSOR_FAMILY_AMD_OPTERON_X3000,
		PROCESSOR_FAMILY_AMD_ZEN,
		// reserved 108-111
		PROCESSOR_FAMILY_HOBBIT = 112U,
		// reserved 113-119
		PROCESSOR_FAMILY_CRUSOE_TM5000 = 120U,
		PROCESSOR_FAMILY_CRUSOE_TM3000,
		PROCESSOR_FAMILY_EFFICEON_TM8000,
		// reserved 123-127
		PROCESSOR_FAMILY_WEITEK = 128U,
		// reserved 129
		PROCESSOR_FAMILY_ITANIUM = 130U,
		PROCESSOR_FAMILY_AMD_ATHLON_64,
		PROCESSOR_FAMILY_AMD_OPTERON,
		PROCESSOR_FAMILY_AMD_SEMPRON,
		PROCESSOR_FAMILY_AMD_TURION_64_MOBILE,
		PROCESSOR_FAMILY_AMD_OPTERON_DUAL_CORE,
		PROCESSOR_FAMILY_AMD_ATHLON_64_X2_DUAL_CORE,
		PROCESSOR_FAMILY_AMD_ATHLON_64_X2_MOBILE,
		PROCESSOR_FAMILY_AMD_OPTERON_QUAD_CORE,
		PROCESSOR_FAMILY_AMD_OPTERON_GEN3,
		PROCESSOR_FAMILY_AMD_PHENOM_FX_QUAD_CORE,
		PROCESSOR_FAMILY_AMD_PHENOM_X4_QUAD_CORE,
		PROCESSOR_FAMILY_AMD_PHENOM_X2_DUAL_CORE,
		PROCESSOR_FAMILY_AMD_ATHLON_X2_DUAL_CORE,
		PROCESSOR_FAMILY_PARISC,
		PROCESSOR_FAMILY_PARISC_8500,
		PROCESSOR_FAMILY_PARISC_8000,
		PROCESSOR_FAMILY_PARISC_7300LC,
		PROCESSOR_FAMILY_PARISC_7200,
		PROCESSOR_FAMILY_PARISC_7100LC,
		PROCESSOR_FAMILY_PARISC_7100,
		// reserved 151-159
		PROCESSOR_FAMILY_V30 = 160U,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_3200,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_3000,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_5300,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_5100,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_5000,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_LV,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_ULV,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_7100,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_5400,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_5200,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_7200,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_7300,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_7400,
		PROCESSOR_FAMILY_INTEL_XEON_MULTI_CORE_7400,
		PROCESSOR_FAMILY_INTEL_PENTIUM_III_XEON,
		PROCESSOR_FAMILY_INTEL_PENTIUM_III_SPEEDSTEP,
		PROCESSOR_FAMILY_INTEL_PENTIUM_4,
		PROCESSOR_FAMILY_INTEL_XEON,
		PROCESSOR_FAMILY_AS400,
		PROCESSOR_FAMILY_INTEL_XEON_MP,
		PROCESSOR_FAMILY_AMD_ATHLON_XP,
		PROCESSOR_FAMILY_AMD_ATHLON_MP,
		PROCESSOR_FAMILY_INTEL_ITANIUM_2,
		PROCESSOR_FAMILY_INTEL_PENTIUM_M,
		PROCESSOR_FAMILY_INTEL_CELERON_D,
		PROCESSOR_FAMILY_INTEL_PENTIUM_D,
		PROCESSOR_FAMILY_INTEL_PENTIUM_EXTREME,
		PROCESSOR_FAMILY_INTEL_CORE_SOLO,
		PROCESSOR_FAMILY_AMD_K7,
		PROCESSOR_FAMILY_INTEL_CORE_2 = PROCESSOR_FAMILY_AMD_K7,
		PROCESSOR_FAMILY_INTEL_CORE_2_DUO,
		PROCESSOR_FAMILY_INTEL_CORE_2_SOLO,
		PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME,
		PROCESSOR_FAMILY_INTEL_CORE_2_QUAD,
		PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME_MOBILE,
		PROCESSOR_FAMILY_INTEL_CORE_2_DUO_MOBILE,
		PROCESSOR_FAMILY_INTEL_CORE_2_SOLO_MOBILE,
		PROCESSOR_FAMILY_INTEL_CORE_I7,
		PROCESSOR_FAMILY_INTEL_CELERON_DUAL_CORE,
		PROCESSOR_FAMILY_IBM390,
		PROCESSOR_FAMILY_G4,
		PROCESSOR_FAMILY_G5,
		PROCESSOR_FAMILY_G6_ESA390,
		PROCESSOR_FAMILY_ZARCHITECTURE,
		PROCESSOR_FAMILY_INTEL_CORE_I5,
		PROCESSOR_FAMILY_INTEL_CORE_I3,
		PROCESSOR_FAMILY_INTEL_CORE_I9,
		PROCESSOR_FAMILY_INTEL_XEON_D,
		// reserved 209
		PROCESSOR_FAMILY_VIA_C7_M = 210U,
		PROCESSOR_FAMILY_VIA_C7_D,
		PROCESSOR_FAMILY_VIA_C7,
		PROCESSOR_FAMILY_VIA_EDEN,
		PROCESSOR_FAMILY_INTEL_XEON_MULTI_CORE,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_3XXX,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_3XXX,
		PROCESSOR_FAMILY_VIA_NANO,
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_5XXX,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_5XXX,
		// reserved 220
		PROCESSOR_FAMILY_INTEL_XEON_DUAL_CORE_7XXX = 221U,
		PROCESSOR_FAMILY_INTEL_XEON_QUAD_CORE_7XXX,
		PROCESSOR_FAMILY_INTEL_XEON_MULTI_CORE_7XXX,
		PROCESSOR_FAMILY_INTEL_XEON_MULTI_CORE_3400,
		// reserved 225-227
		PROCESSOR_FAMILY_AMD_OPTERON_3000 = 228U,
		PROCESSOR_FAMILY_AMD_SEMPRON_II,
		PROCESSOR_FAMILY_AMD_OPTERON_QUAD_CORE_EMBEDDED,
		PROCESSOR_FAMILY_AMD_PHENOM_TRIPLE_CORE,
		PROCESSOR_FAMILY_AMD_TURION_ULTRA_DUAL_CORE,
		PROCESSOR_FAMILY_AMD_TURION_DUAL_CORE_MOBILE,
		PROCESSOR_FAMILY_AMD_ATHLON_DUAL_CORE,
		PROCESSOR_FAMILY_AMD_SEMPRON_SI,
		PROCESSOR_FAMILY_AMD_PHENOM_II,
		PROCESSOR_FAMILY_AMD_ATHLON_II,
		PROCESSOR_FAMILY_AMD_OPTERON_SIX_CORE,
		PROCESSOR_FAMILY_AMD_SEMPRON_M,
		// reserved 240-249
		PROCESSOR_FAMILY_I860 = 250U,
		PROCESSOR_FAMILY_I960,
		// reserved 252-253
		PROCESSOR_FAMILY_EXTENDED = 0xFE,
		PROCESSOR_FAMILY_RESERVED = 0xFF,
		PROCESSOR_FAMILY_ARMV7 = 256U,
		PROCESSOR_FAMILY_ARMV8,
		PROCESSOR_FAMILY_ARMV9,
		PROCESSOR_FAMILY_ARM_RESERVED,
		PROCESSOR_FAMILY_SH3,
		PROCESSOR_FAMILY_SH4,
		// reserved 262-279
		PROCESSOR_FAMILY_ARM = 280U,
		PROCESSOR_FAMILY_STRONGARM,
		// reserved 282-299
		PROCESSOR_FAMILY_6X86 = 300U,
		PROCESSOR_FAMILY_MEDIAGX,
		PROCESSOR_FAMILY_MII,
		// reserved 303-319
		PROCESSOR_FAMILY_WINCHIP = 320U,
		// reserved 321-349
		PROCESSOR_FAMILY_DSP = 350U,
		// reserved 351-499
		PROCESSOR_FAMILY_VIDEO_PROCESSOR = 500U,
		// reserved 501-511
		PROCESSOR_FAMILY_RV32 = 512U,
		PROCESSOR_FAMILY_RV64,
		PROCESSOR_FAMILY_RV128,
		// reserved 515-599
		PROCESSOR_FAMILY_LOONGARCH = 600U,
		PROCESSOR_FAMILY_LOONGSON_1,
		PROCESSOR_FAMILY_LOONGSON_2,
		PROCESSOR_FAMILY_LOONGSON_3,
		PROCESSOR_FAMILY_LOONGSON_2K,
		PROCESSOR_FAMILY_LOONGSON_3A,
		PROCESSOR_FAMILY_LOONGSON_3B,
		PROCESSOR_FAMILY_LOONGSON_3C,
		PROCESSOR_FAMILY_LOONGSON_3D,
		PROCESSOR_FAMILY_LOONGSON_3E,
		PROCESSOR_FAMILY_LOONGSON_DUAL_CORE_2K_2XXX,
		// reserved 611-619
		PROCESSOR_FAMILY_LOONGSON_QUAD_CORE_3A_5XXX = 620U,
		PROCESSOR_FAMILY_LOONGSON_MULTI_CORE_3A_5XXX,
		PROCESSOR_FAMILY_LOONGSON_QUAD_CORE_3B_5XXX,
		PROCESSOR_FAMILY_LOONGSON_MULTI_CORE_3B_5XXX,
		PROCESSOR_FAMILY_LOONGSON_MULTI_CORE_3C_5XXX,
		PROCESSOR_FAMILY_LOONGSON_MULTI_CORE_3D_5XXX,
		// reserved 624-767
		PROCESSOR_FAMILY_INTEL_CORE_3 = 768U,
		PROCESSOR_FAMILY_INTEL_CORE_5,
		PROCESSOR_FAMILY_INTEL_CORE_7,
		PROCESSOR_FAMILY_INTEL_CORE_9,
		PROCESSOR_FAMILY_INTEL_CORE_ULTRA_3,
		PROCESSOR_FAMILY_INTEL_CORE_ULTRA_5,
		PROCESSOR_FAMILY_INTEL_CORE_ULTRA_7,
		PROCESSOR_FAMILY_INTEL_CORE_ULTRA_9,
		// reserved 776-65533
	};

	using ProcessorUpgrade_t = std::uint8_t;
	enum EProcessorUpgrade : std::uint8_t
	{
		PROCESSOR_UPGRADE_OTHER = 1U,
		PROCESSOR_UPGRADE_UNKNOWN,
		PROCESSOR_UPGRADE_DAUGHTER_BOARD,
		PROCESSOR_UPGRADE_SOCKET_ZIF,
		PROCESSOR_UPGRADE_REPLACEABLE_PIGGY_BACK,
		PROCESSOR_UPGRADE_NONE,
		PROCESSOR_UPGRADE_SOCKET_LIF,
		PROCESSOR_UPGRADE_SLOT_1,
		PROCESSOR_UPGRADE_SLOT_2,
		PROCESSOR_UPGRADE_SOCKET_370PIN,
		PROCESSOR_UPGRADE_SLOT_A,
		PROCESSOR_UPGRADE_SLOT_M,
		PROCESSOR_UPGRADE_SOCKET_423,
		PROCESSOR_UPGRADE_SOCKET_A,
		PROCESSOR_UPGRADE_SOCKET_462 = PROCESSOR_UPGRADE_SOCKET_A,
		PROCESSOR_UPGRADE_SOCKET_478,
		PROCESSOR_UPGRADE_SOCKET_454,
		PROCESSOR_UPGRADE_SOCKET_940,
		PROCESSOR_UPGRADE_SOCKET_939,
		PROCESSOR_UPGRADE_SOCKET_MPGA604,
		PROCESSOR_UPGRADE_SOCKET_LGA771,
		PROCESSOR_UPGRADE_SOCKET_LGA775,
		PROCESSOR_UPGRADE_SOCKET_S1,
		PROCESSOR_UPGRADE_SOCKET_AM2,
		PROCESSOR_UPGRADE_SOCKET_F,
		PROCESSOR_UPGRADE_SOCKET_1207 = PROCESSOR_UPGRADE_SOCKET_F,
		PROCESSOR_UPGRADE_SOCKET_LGA1366,
		PROCESSOR_UPGRADE_SOCKET_G34,
		PROCESSOR_UPGRADE_SOCKET_AM3,
		PROCESSOR_UPGRADE_SOCKET_C32,
		PROCESSOR_UPGRADE_SOCKET_LGA1156,
		PROCESSOR_UPGRADE_SOCKET_LGA1567,
		PROCESSOR_UPGRADE_SOCKET_PGA988A,
		PROCESSOR_UPGRADE_SOCKET_BGA1288,
		PROCESSOR_UPGRADE_SOCKET_RPGA988B,
		PROCESSOR_UPGRADE_SOCKET_BGA1023,
		PROCESSOR_UPGRADE_SOCKET_BGA1224,
		PROCESSOR_UPGRADE_SOCKET_LGA1155,
		PROCESSOR_UPGRADE_SOCKET_LGA1356,
		PROCESSOR_UPGRADE_SOCKET_LGA2011,
		PROCESSOR_UPGRADE_SOCKET_FS1,
		PROCESSOR_UPGRADE_SOCKET_FS2,
		PROCESSOR_UPGRADE_SOCKET_FM1,
		PROCESSOR_UPGRADE_SOCKET_FM2,
		PROCESSOR_UPGRADE_SOCKET_LGA2011_3,
		PROCESSOR_UPGRADE_SOCKET_LGA1356_3,
		PROCESSOR_UPGRADE_SOCKET_LGA1150,
		PROCESSOR_UPGRADE_SOCKET_BGA1168,
		PROCESSOR_UPGRADE_SOCKET_BGA1234,
		PROCESSOR_UPGRADE_SOCKET_BGA1364,
		PROCESSOR_UPGRADE_SOCKET_AM4,
		PROCESSOR_UPGRADE_SOCKET_LGA1151,
		PROCESSOR_UPGRADE_SOCKET_BGA1356,
		PROCESSOR_UPGRADE_SOCKET_BGA1440,
		PROCESSOR_UPGRADE_SOCKET_BGA1515,
		PROCESSOR_UPGRADE_SOCKET_LGA3647_1,
		PROCESSOR_UPGRADE_SOCKET_SP3,
		PROCESSOR_UPGRADE_SOCKET_SP3R2,
		PROCESSOR_UPGRADE_SOCKET_LGA2066,
		PROCESSOR_UPGRADE_SOCKET_BGA1392,
		PROCESSOR_UPGRADE_SOCKET_BGA1510,
		PROCESSOR_UPGRADE_SOCKET_BGA1528,
		PROCESSOR_UPGRADE_SOCKET_LGA4189,
		PROCESSOR_UPGRADE_SOCKET_LGA1200,
		PROCESSOR_UPGRADE_SOCKET_LGA4677,
		PROCESSOR_UPGRADE_SOCKET_LGA1700,
		PROCESSOR_UPGRADE_SOCKET_BGA1744,
		PROCESSOR_UPGRADE_SOCKET_BGA1781,
		PROCESSOR_UPGRADE_SOCKET_BGA1211,
		PROCESSOR_UPGRADE_SOCKET_BGA2422,
		PROCESSOR_UPGRADE_SOCKET_LGA1211,
		PROCESSOR_UPGRADE_SOCKET_LGA2422,
		PROCESSOR_UPGRADE_SOCKET_LGA5773,
		PROCESSOR_UPGRADE_SOCKET_BGA5773,
		PROCESSOR_UPGRADE_SOCKET_AM5,
		PROCESSOR_UPGRADE_SOCKET_SP5,
		PROCESSOR_UPGRADE_SOCKET_SP6,
		PROCESSOR_UPGRADE_SOCKET_BGA883,
		PROCESSOR_UPGRADE_SOCKET_BGA1190,
		PROCESSOR_UPGRADE_SOCKET_BGA4129,
		PROCESSOR_UPGRADE_SOCKET_LGA4710,
		PROCESSOR_UPGRADE_SOCKET_LGA7529,
		PROCESSOR_UPGRADE_SOCKET_BGA1964,
		PROCESSOR_UPGRADE_SOCKET_BGA1792,
		PROCESSOR_UPGRADE_SOCKET_BGA2049,
		PROCESSOR_UPGRADE_SOCKET_BGA2551,
		PROCESSOR_UPGRADE_SOCKET_LGA1851,
		PROCESSOR_UPGRADE_SOCKET_BGA2114,
		PROCESSOR_UPGRADE_SOCKET_BGA2833,
		PROCESSOR_UPGRADE_WILDCARD = 0xFF
	};

	using ProcessorCharacteristics_t = std::uint16_t;
	enum EProcessorCharacteristics : std::uint16_t
	{
		PROCESSOR_CHARACTERISTICS_UNKNOWN = (1U << 1U),
		PROCESSOR_CHARACTERISTICS_64BIT_CAPABLE = (1U << 2U),
		PROCESSOR_CHARACTERISTICS_MULTI_CORE = (1U << 3U),
		PROCESSOR_CHARACTERISTICS_HARDWARE_THREAD = (1U << 4U),
		PROCESSOR_CHARACTERISTICS_EXECUTE_PROTECTION = (1U << 5U),
		PROCESSOR_CHARACTERISTICS_ENHANCED_VIRTUALIZATION = (1U << 6U),
		PROCESSOR_CHARACTERISTICS_POWER_CONTROL = (1U << 7U),
		PROCESSOR_CHARACTERISTICS_128BIT_CAPABLE = (1U << 8U),
		PROCESSOR_CHARACTERISTICS_ARM64_SOC_ID = (1U << 9U)
	};

	struct ProcessorInformation_t
	{
		// 2.0+
		StringIndex_t nSocketDesignation; // 0x04
		ProcessorType_t nType; // 0x05
		ProcessorFamily_t nFamily; // 0x06
		StringIndex_t nManufacturer; // 0x07
		union
		{
			std::uint64_t ullProcessorID; 
			struct
			{
				std::uint32_t uEax;
				std::uint32_t uEdx;
			} X86;
			struct
			{
				std::uint32_t uMidr;
				std::uint32_t uReserved;
			} ARM32;
			struct
			{
				union
				{
					struct
					{
						std::uint16_t uSip;
						std::uint8_t nSipIdentificationCode;
						std::uint8_t nSipBankIndex;
						std::uint32_t uRevisionValue;
					} SoC;
					std::uint32_t uMidreEl1;
					std::uint32_t uReserved;
				};
			} ARM64;
			struct
			{
				std::uint64_t ullMachineVendorID;
			} RV;
			struct
			{
				// https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html#_cpucfg
				std::uint64_t ullProcessorCoreID;
			} LoongArch;
		}; // 0x08
		StringIndex_t nVersion; // 0x10
		union
		{
			union
			{
				struct
				{
					VoltageFlags_t uVoltageFlags : 3;
					std::uint8_t uReserved0 : 4;
				};
				std::uint8_t uVoltageValue : 7;
			};
			std::uint8_t bVoltageLegacyMode : 1;
		}; // 0x11 // deprecated since 3.8.0
		std::uint16_t uExternalClock; // 0x12
		std::uint16_t uMaxSpeed; // 0x14
		std::uint16_t uCurrentSpeed; // 0x16
		struct
		{
			std::uint8_t nStatus : 3;
			std::uint8_t uReserved1 : 3;
			std::uint8_t bSocketPopulated : 1;
			std::uint8_t uReserved2 : 1;
		}; // 0x18
		ProcessorUpgrade_t nUpgrade; // 0x19
		// 2.1+
		std::uint16_t uL1CacheHandle; // 0x1A
		std::uint16_t uL2CacheHandle; // 0x1C
		std::uint16_t uL3CacheHandle; // 0x1E
		// 2.3+
		StringIndex_t nSerialNumber; // 0x20
		StringIndex_t nAssetTag; // 0x21
		StringIndex_t nPartNumber; // 0x22
		// 2.5+
		std::uint8_t nCoreCount; // 0x23
		std::uint8_t nCoreEnabled; // 0x24
		std::uint8_t nThreadCount; // 0x25
		ProcessorCharacteristics_t uCharacteristics; // 0x26
		// 2.6+
		ProcessorFamilyExtended_t nFamilyExtended; // 0x28
		// 3.0+
		std::uint16_t nCoreCountExtended; // 0x2A
		std::uint16_t nCoreEnabledExtended; // 0x2C
		std::uint16_t nThreadCountExtended; // 0x2E
		// 3.6+
		std::uint16_t nThreadEnabled; // 0x30
		// 3.8+
		StringIndex_t nSocketType; // 0x32
	};

	using MemoryControllerErrorDetectingMethod_t = std::uint8_t;
	enum EMemoryControllerErrorDetectingMethod : std::uint8_t
	{
		MEMORY_CONTROLLER_ERROR_DETECTING_OTHER = 1U,
		MEMORY_CONTROLLER_ERROR_DETECTING_UNKNOWN,
		MEMORY_CONTROLLER_ERROR_DETECTING_NONE,
		MEMORY_CONTROLLER_ERROR_DETECTING_8BIT_PARITY,
		MEMORY_CONTROLLER_ERROR_DETECTING_32BIT_ECC,
		MEMORY_CONTROLLER_ERROR_DETECTING_64BIT_ECC,
		MEMORY_CONTROLLER_ERROR_DETECTING_128BIT_ECC,
		MEMORY_CONTROLLER_ERROR_DETECTING_CRC
	};

	using MemoryControllerErrorCorrectingCapability_t = std::uint8_t;
	enum EMemoryControllerErrorCorrectingCapability : std::uint8_t
	{
		MEMORY_CONTROLLER_ERROR_CORRECTING_OTHER = 1U << 0U,
		MEMORY_CONTROLLER_ERROR_CORRECTING_UNKNOWN = 1U << 1U,
		MEMORY_CONTROLLER_ERROR_CORRECTING_NONE = 1U << 2U,
		MEMORY_CONTROLLER_ERROR_CORRECTING_SINGLE_BIT = 1U << 3U,
		MEMORY_CONTROLLER_ERROR_CORRECTING_DOUBLE_BIT = 1U << 4U,
		MEMORY_CONTROLLER_ERROR_CORRECTING_SCRUBBING = 1U << 5U
	};

	using MemoryControllerInterleave_t = std::uint8_t;
	enum EEMemoryControllerInterleave : std::uint8_t
	{
		MEMORY_CONTROLLER_INTERLEAVE_OTHER = 1U,
		MEMORY_CONTROLLER_INTERLEAVE_UNKNOWN,
		MEMORY_CONTROLLER_INTERLEAVE_ONE_WAY,
		MEMORY_CONTROLLER_INTERLEAVE_TWO_WAY,
		MEMORY_CONTROLLER_INTERLEAVE_FOUR_WAY,
		MEMORY_CONTROLLER_INTERLEAVE_EIGHT_WAY,
		MEMORY_CONTROLLER_INTERLEAVE_SIXTEEN_WAY
	};

	using MemoryControllerSpeed_t = std::uint16_t;
	enum EEMemoryControllerSpeed : std::uint16_t
	{
		MEMORY_CONTROLLER_SPEED_OTHER = 1U << 0U,
		MEMORY_CONTROLLER_SPEED_UNKNOWN = 1U << 1U,
		MEMORY_CONTROLLER_SPEED_70NS = 1U << 2U,
		MEMORY_CONTROLLER_SPEED_60NS = 1U << 3U,
		MEMORY_CONTROLLER_SPEED_50NS = 1U << 4U
	};

	using MemoryModuleType_t = std::uint16_t;
	enum EMemoryModuleType : std::uint16_t
	{
		MEMORY_MODULE_OTHER = 1U << 0U,
		MEMORY_MODULE_UNKNOWN = 1U << 1U,
		MEMORY_MODULE_STANDARD = 1U << 2U,
		MEMORY_MODULE_FAST_PAGE_MODE = 1U << 3U,
		MEMORY_MODULE_EDO = 1U << 4U,
		MEMORY_MODULE_PARITY = 1U << 5U,
		MEMORY_MODULE_ECC = 1U << 6U,
		MEMORY_MODULE_SIMM = 1U << 7U,
		MEMORY_MODULE_DIMM = 1U << 8U,
		MEMORY_MODULE_BURST_EDO = 1U << 9U,
		MEMORY_MODULE_SDRAM = 1U << 10U
	};

	// obsolete since 2.1
	struct MemoryControllerInformation_t
	{
		MemoryControllerErrorDetectingMethod_t nErrorDetectingMethod; // 0x4
		MemoryControllerErrorCorrectingCapability_t uErrorCorrectingCapability; // 0x5
		MemoryControllerInterleave_t nSupportedInterleave; // 0x6
		MemoryControllerInterleave_t nCurrentInterleave; // 0x7
		std::uint8_t nMaxMemoryModuleSize; // 0x8
		MemoryControllerSpeed_t uSupportedSpeeds; // 0x9
		MemoryModuleType_t uSupportedTypes; // 0xB
		struct
		{
			VoltageFlags_t uMemoryModuleVoltage : 3;
			std::uint8_t uReserved : 5;
		}; // 0xD
		std::uint8_t nAssociatedMemorySlotsCount; // 0xE
		std::uint16_t arrMemoryModuleConfigurationHandles[]; // 0xF
		// 2.1+
		// @note: fields below require manual parsing
		//MemoryControllerErrorCorrectingCapability_t uEnabledErrorCorrectingCapabilities; // 0xF + (0x2*N)
	};

#define Q_SMBIOS_MEMORY_MODULE_SIZE_NOT_DETERMINABLE 0x7D
#define Q_SMBIOS_MEMORY_MODULE_SIZE_NOT_ENABLED 0x7E
#define Q_SMBIOS_MEMORY_MODULE_SIZE_NOT_INSTALLED 0x7F

#define Q_SMBIOS_MEMORY_MODULE_ERROR_LOG (1U << 2U)

	// obsolete since 2.1
	struct MemoryModuleInformation_t
	{
		StringIndex_t nSocketDesignation; // 0x4
		std::uint8_t uBankConnections; // 0x5
		std::uint8_t uCurrentSpeed; // 0x6
		MemoryModuleType_t uCurrentMemoryType; // 0x7
		struct
		{
			std::uint8_t nInstalledSize : 7;
			std::uint8_t bInstalledDoubleBank : 1;
		}; // 0x9
		struct
		{
			std::uint8_t nEnabledSize : 7;
			std::uint8_t bEnabledDoubleBank : 1;
		}; // 0xA
		std::uint8_t uErrorStatus; // 0xB
	};

	using CacheLocation_t = std::uint16_t;
	enum ECacheLocation_t : std::uint8_t
	{
		CACHE_LOCATION_INTERNAL = 0U,
		CACHE_LOCATION_EXTERNAL,
		CACHE_LOCATION_UNKNOWN = 3U
	};

	using CacheOperationalMode_t = std::uint16_t;
	enum ECacheOperationalMode_t : std::uint8_t
	{
		CACHE_OPERATIONAL_MODE_WRITE_THROUGH = 0U,
		CACHE_OPERATIONAL_MODE_WRITE_BACK,
		CACHE_OPERATIONAL_MODE_VARIES,
		CACHE_OPERATIONAL_MODE_UNKNOWN
	};

	using CacheSRAMType_t = std::uint16_t;
	enum ECacheSRAMType : std::uint16_t
	{
		CACHE_SRAM_OTHER = 1U << 0U,
		CACHE_SRAM_UNKNOWN = 1U << 1U,
		CACHE_SRAM_NON_BURST = 1U << 2U,
		CACHE_SRAM_BURST = 1U << 3U,
		CACHE_SRAM_PIPELINE_BURST = 1U << 4U,
		CACHE_SRAM_SYNCHRONOUS = 1U << 5U,
		CACHE_SRAM_ASYNCHRONOUS = 1U << 6U
	};

	using CacheErrorCorrectionType_t = std::uint8_t;
	enum ECacheErrorCorrectionType : std::uint8_t
	{
		CACHE_ERROR_CORRECTION_OTHER = 1U,
		CACHE_ERROR_CORRECTION_UNKNOWN,
		CACHE_ERROR_CORRECTION_NONE,
		CACHE_ERROR_CORRECTION_PARITY,
		CACHE_ERROR_CORRECTION_SINGLE_BIT_ECC,
		CACHE_ERROR_CORRECTION_MULTI_BIT_ECC
	};

	using CacheSystemType_t = std::uint8_t;
	enum ECacheSystemType : std::uint8_t
	{
		CACHE_SYSTEM_OTHER = 1U,
		CACHE_SYSTEM_UNKNOWN,
		CACHE_SYSTEM_INSTRUCTION,
		CACHE_SYSTEM_DATA,
		CACHE_SYSTEM_UNIFIED
	};

	using CacheAssociativity_t = std::uint8_t;
	enum ECacheAssociativity : std::uint8_t
	{
		CACHE_ASSOCIATIVITY_OTHER = 1U,
		CACHE_ASSOCIATIVITY_UNKNOWN,
		CACHE_ASSOCIATIVITY_DIRECT_MAPPED,
		CACHE_ASSOCIATIVITY_2_WAY_SET,
		CACHE_ASSOCIATIVITY_4_WAY_SET,
		CACHE_ASSOCIATIVITY_FULL,
		CACHE_ASSOCIATIVITY_8_WAY_SET,
		CACHE_ASSOCIATIVITY_16_WAY_SET,
		CACHE_ASSOCIATIVITY_12_WAY_SET,
		CACHE_ASSOCIATIVITY_24_WAY_SET,
		CACHE_ASSOCIATIVITY_32_WAY_SET,
		CACHE_ASSOCIATIVITY_48_WAY_SET,
		CACHE_ASSOCIATIVITY_64_WAY_SET,
		CACHE_ASSOCIATIVITY_20_WAY_SET
	};

	struct CacheInformation_t
	{
		StringIndex_t nSocketDesignation; // 0x04
		union
		{
			std::uint16_t uConfiguration;
			struct
			{
				std::uint16_t nLevel : 2;
				std::uint16_t bSocketed : 1;
				std::uint16_t bReserved : 1;
				CacheLocation_t nLocation : 2;
				std::uint16_t bEnabled : 1;
				CacheOperationalMode_t nOperationalMode : 2;
				std::uint16_t uReserved : 7;
			};
		}; // 0x05
		struct
		{
			std::uint16_t nMaxSize : 15;
			std::uint16_t nMaxSizeGranularity : 1;
		}; // 0x07
		struct
		{
			std::uint16_t nInstalledSize : 15;
			std::uint16_t nInstalledSizeGranularity : 1;
		}; // 0x09
		CacheSRAMType_t uSupportedSRAMType; // 0x0B
		CacheSRAMType_t uCurrentSRAMType; // 0x0D
		// 2.1+
		std::uint8_t uSpeed; // 0x0F
		CacheErrorCorrectionType_t nErrorCorrectionType; // 0x10
		CacheSystemType_t nSystemCacheType; // 0x11
		CacheAssociativity_t nAssociativity; // 0x12
		// 3.1+
		struct
		{
			std::uint32_t nMaxSizeExtended : 31;
			std::uint32_t nMaxSizeExtendedGranularity : 1;
		}; // 0x13
		struct
		{
			std::uint32_t nInstalledSizeExtended : 31;
			std::uint32_t nInstalledSizeExtendedGranularity : 1;
		}; // 0x17
	};

	using PortConnectorType_t = std::uint8_t;
	enum EPortConnectorType : std::uint8_t
	{
		PORT_CONNECTOR_NONE = 0U,
		PORT_CONNECTOR_CENTRONICS,
		PORT_CONNECTOR_MINI_CENTRONICS,
		PORT_CONNECTOR_PROPRIETARY,
		PORT_CONNECTOR_DB_25PIN_MALE,
		PORT_CONNECTOR_DB_25PIN_FEMALE,
		PORT_CONNECTOR_DB_15PIN_MALE,
		PORT_CONNECTOR_DB_15PIN_FEMALE,
		PORT_CONNECTOR_DB_9PIN_MALE,
		PORT_CONNECTOR_DB_9PIN_FEMALE,
		PORT_CONNECTOR_RJ11,
		PORT_CONNECTOR_RJ45,
		PORT_CONNECTOR_50PIN_MINISCSI,
		PORT_CONNECTOR_MINI_DIN,
		PORT_CONNECTOR_MICRO_DIN,
		PORT_CONNECTOR_PS2,
		PORT_CONNECTOR_INFRARED,
		PORT_CONNECTOR_HP_HIL,
		PORT_CONNECTOR_ACCESS_BUS,
		PORT_CONNECTOR_USB = PORT_CONNECTOR_ACCESS_BUS,
		PORT_CONNECTOR_SSA_SCSI,
		PORT_CONNECTOR_CIRCULAR_DIN8_MALE,
		PORT_CONNECTOR_CIRCULAR_DIN8_FEMALE,
		PORT_CONNECTOR_ON_BOARD_IDE,
		PORT_CONNECTOR_ON_BOARD_FLOPPY,
		PORT_CONNECTOR_9PIN_DUAL_INLINE,
		PORT_CONNECTOR_25PIN_DUAL_INLINE,
		PORT_CONNECTOR_50PIN_DUAL_INLINE,
		PORT_CONNECTOR_68PIN_DUAL_INLINE,
		PORT_CONNECTOR_ON_BOARD_SOUND_FROM_CDROM,
		PORT_CONNECTOR_MINI_CENTRNICS_TYPE_14,
		PORT_CONNECTOR_MINI_CENTRNICS_TYPE_26,
		PORT_CONNECTOR_MINI_JACK,
		PORT_CONNECTOR_BNC,
		PORT_CONNECTOR_1394,
		PORT_CONNECTOR_SATA,
		PORT_CONNECTOR_USB_TYPE_C,
		// reserved 36-159
		PORT_CONNECTOR_PC_98 = 160U,
		PORT_CONNECTOR_PC_98HIRESO,
		PORT_CONNECTOR_PC_H98,
		PORT_CONNECTOR_PC_98NOTE,
		PORT_CONNECTOR_PC_98FULL,
		PORT_CONNECTOR_OTHER = 0xFF
	};

	using PortType_t = std::uint8_t;
	enum EPortType : std::uint8_t
	{
		PORT_NONE = 0U,
		PORT_PARALLEL_XT_AT_COMPATIBLE,
		PORT_PARALLEL_PS2,
		PORT_PARALLEL_ECP,
		PORT_PARALLEL_EPP,
		PORT_PARALLEL_ECP_EPP,
		PORT_SERIAL_XT_AT_COMPATIBLE,
		PORT_SERIAL_16450_COMPATIBLE,
		PORT_SERIAL_16550_COMPATIBLE,
		PORT_SERIAL_16550A_COMPATIBLE,
		PORT_SCSI,
		PORT_MIDI,
		PORT_JOYSTICK,
		PORT_KEYBOARD,
		PORT_MOUSE,
		PORT_SSCA_SCSI,
		PORT_USB,
		PORT_FIREWIRE,
		PORT_PCMCIA_TYPE_I,
		PORT_PCMCIA_TYPE_II,
		PORT_PCMCIA_TYPE_III,
		PORT_CARD_BUS,
		PORT_ACCESS_BUS,
		PORT_SCSI_II,
		PORT_SCSI_WIDE,
		PORT_PC_98,
		PORT_PC_98HIRESO,
		PORT_PC_H98,
		PORT_VIDEO,
		PORT_AUDIO,
		PORT_MODEM,
		PORT_NETWORK,
		PORT_SATA,
		PORT_SAS,
		PORT_MFDP,
		PORT_THUNDERBOLT,
		// reserved 36-159
		PORT_8251_COMPATIBLE = 160U,
		PORT_8251_FIFO_COMPATIBLE,
		PORT_OTHER = 0xFF
	};

	struct PortConnectorInformation_t
	{
		// 2.0+
		StringIndex_t nInternalReferenceDesignator; // 0x04
		PortConnectorType_t nInternalConnectorType; // 0x05
		StringIndex_t nExternalReferenceDesignator; // 0x06
		PortConnectorType_t nExternalConnectorType; // 0x07
		PortType_t nPortType; // 0x08
	};

	using SlotType_t = std::uint8_t;
	enum ESlotType : std::uint8_t
	{
		SLOT_OTHER = 1U,
		SLOT_UNKNOWN,
		SLOT_ISA,
		SLOT_MCA,
		SLOT_EISA,
		SLOT_PCI,
		SLOT_PCMCIA,
		SLOT_VLVESA,
		SLOT_PROPRIETARY,
		SLOT_PROCESSOR_CARD,
		SLOT_PROPRIETARY_MEMORY_CARD,
		SLOT_IO_RISER_CARD,
		SLOT_NUBUS,
		SLOT_PCI_66MHZ,
		SLOT_AGP,
		SLOT_AGP_2X,
		SLOT_AGP_4X,
		SLOT_PCI_X,
		SLOT_AGP_8X,
		SLOT_M2_SOCKET_1_DP,
		SLOT_M2_SOCKET_1_SD,
		SLOT_M2_SOCKET_2,
		SLOT_M2_SOCKET_3,
		SLOT_MXM_TYPE_I,
		SLOT_MXM_TYPE_II,
		SLOT_MXM_TYPE_III,
		SLOT_MXM_TYPE_III_HE,
		SLOT_MXM_TYPE_IV,
		SLOT_MXM3_TYPE_A,
		SLOT_MXM3_TYPE_B,
		SLOT_PCIE2_U2,
		SLOT_PCIE3_U2,
		SLOT_PCIE_MINI_52PIN_BOTTOM,
		SLOT_PCIE_MINI_52PIN,
		SLOT_PCIE_MINI_76PIN,
		SLOT_PCIE4_U2,
		SLOT_PCIE5_U2,
		SLOT_OCP_NIC3_SFF,
		SLOT_OCP_NIC3_LFF,
		SLOT_OCP_NIC3,
		// reserved 41-47
		SLOT_CXL_FLEXBUS1 = 48U,
		// reserved 49-159
		SLOT_PC98_C20 = 160U,
		SLOT_PC98_C24,
		SLOT_PC98_E,
		SLOT_PC98_LOCAL_BUS,
		SLOT_PC98_CARD,
		SLOT_PCIE,
		SLOT_PCIE_X1,
		SLOT_PCIE_X2,
		SLOT_PCIE_X4,
		SLOT_PCIE_X8,
		SLOT_PCIE_X16,
		SLOT_PCIE2,
		SLOT_PCIE2_X1,
		SLOT_PCIE2_X2,
		SLOT_PCIE2_X4,
		SLOT_PCIE2_X8,
		SLOT_PCIE2_X16,
		SLOT_PCIE3,
		SLOT_PCIE3_X1,
		SLOT_PCIE3_X2,
		SLOT_PCIE3_X4,
		SLOT_PCIE3_X8,
		SLOT_PCIE3_X16,
		SLOT_PCIE4,
		SLOT_PCIE4_X1,
		SLOT_PCIE4_X2,
		SLOT_PCIE4_X4,
		SLOT_PCIE4_X8,
		SLOT_PCIE4_X16,
		SLOT_PCIE5,
		SLOT_PCIE5_X1,
		SLOT_PCIE5_X2,
		SLOT_PCIE5_X4,
		SLOT_PCIE5_X8,
		SLOT_PCIE5_X16,
		SLOT_PCIE6,
		SLOT_EDSFF_E1,
		SLOT_EDSFF_E3
	};

	using SlotDataBusWidth_t = std::uint8_t;
	enum ESlotDataBusWidth : std::uint8_t
	{
		SLOT_DATA_BUS_WIDTH_OTHER = 1U,
		SLOT_DATA_BUS_WIDTH_UNKNOWN,
		SLOT_DATA_BUS_WIDTH_8BIT,
		SLOT_DATA_BUS_WIDTH_16BIT,
		SLOT_DATA_BUS_WIDTH_32BIT,
		SLOT_DATA_BUS_WIDTH_64BIT,
		SLOT_DATA_BUS_WIDTH_128BIT,
		SLOT_DATA_BUS_WIDTH_X1,
		SLOT_DATA_BUS_WIDTH_X2,
		SLOT_DATA_BUS_WIDTH_X4,
		SLOT_DATA_BUS_WIDTH_X8,
		SLOT_DATA_BUS_WIDTH_X12,
		SLOT_DATA_BUS_WIDTH_X16,
		SLOT_DATA_BUS_WIDTH_X32
	};

	using SlotCurrentUsage_t = std::uint8_t;
	enum ESlotCurrentUsage : std::uint8_t
	{
		SLOT_CURRENT_USAGE_OTHER = 1U,
		SLOT_CURRENT_USAGE_UNKNOWN,
		SLOT_CURRENT_USAGE_AVAILABLE,
		SLOT_CURRENT_USAGE_IN_USE,
		SLOT_CURRENT_USAGE_UNAVAILABLE
	};

	using SlotCharacteristics_t = std::uint8_t;
	enum ESlotCharacteristics : std::uint8_t
	{
		SLOT_CHARACTERISTICS_UNKNOWN = (1U << 0U),
		SLOT_CHARACTERISTICS_PROVIDES_5_0V = (1U << 1U),
		SLOT_CHARACTERISTICS_PROVIDES_3_3V = (1U << 2U),
		SLOT_CHARACTERISTICS_SHARED = (1U << 3U),
		SLOT_CHARACTERISTICS_PCCARD_SUPPORT_PCCARD16 = (1U << 4U),
		SLOT_CHARACTERISTICS_PCCARD_SUPPORT_CARDBUS = (1U << 5U),
		SLOT_CHARACTERISTICS_PCCARD_SUPPORT_ZOOM_VIDEO = (1U << 6U),
		SLOT_CHARACTERISTICS_PCCARD_SUPPORT_MODEM_RING_RESUME = (1U << 7U)
	};

	using SlotCharacteristicsExtended_t = std::uint8_t;
	enum ESlotCharacteristicsExtended : std::uint8_t
	{
		SLOT_CHARACTERISTICS_PCI_SUPPORT_PME = (1U << 0U),
		SLOT_CHARACTERISTICS_SUPPORT_HOT_PLUG = (1U << 1U),
		SLOT_CHARACTERISTICS_PCI_SUPPORT_SMBUS = (1U << 2U),
		SLOT_CHARACTERISTICS_PCIE_SUPPORT_BIFURCATION = (1U << 3U),
		SLOT_CHARACTERISTICS_SUPPORT_ASYNC_REMOVAL = (1U << 4U),
		SLOT_CHARACTERISTICS_FLEXBUS_CXL1 = (1U << 5U),
		SLOT_CHARACTERISTICS_FLEXBUS_CXL2 = (1U << 6U),
		SLOT_CHARACTERISTICS_FLEXBUS_CXL3 = (1U << 7U)
	};

	using SlotLength_t = std::uint8_t;
	enum ESlotLength : std::uint8_t
	{
		SLOT_LENGTH_OTHER = 1U,
		SLOT_LENGTH_UNKNOWN,
		SLOT_LENGTH_SHORT,
		SLOT_LENGTH_LONG,
		SLOT_LENGTH_2_5_DRIVE,
		SLOT_LENGTH_3_5_DRIVE
	};

	using SlotHeight_t = std::uint8_t;
	enum ESlotHeight : std::uint8_t
	{
		SLOT_HEIGHT_NOT_APPLICABLE = 0U,
		SLOT_HEIGHT_OTHER,
		SLOT_HEIGHT_UNKNOWN,
		SLOT_HEIGHT_FULL,
		SLOT_HEIGHT_LOW_PROFILE
	};

	struct SystemSlotsPeerGroup_t
	{
		std::uint16_t uSegmentGroupNumber; // 0x0
		std::uint8_t uBusNumber; // 0x2
		struct
		{
			std::uint8_t uFunctionNumber : 3;
			std::uint8_t uDeviceNumber : 5;
		}; // 0x3
		std::uint8_t nDataBusWidth; // 0x4
	};

	struct SystemSlots_t
	{
		// 2.0+
		StringIndex_t nSlotDesignation; // 0x04
		SlotType_t nSlotType; // 0x05
		SlotDataBusWidth_t nSlotDataBusWidth; // 0x06
		SlotCurrentUsage_t nCurrentUsage; // 0x07
		SlotLength_t nSlotLength; // 0x08
		union
		{
			std::uint16_t uSlotID; 
			struct
			{
				std::uint8_t nLogicalSlot;
			} MCA;
			struct
			{
				std::uint8_t nLogicalSlot;
			} EISA;
			struct
			{
				std::uint16_t nUniqueID;
			} PCI;
			struct
			{
				std::uint8_t nAdapter;
				std::uint8_t nSocket;
			} PCMCIA;
		}; // 0x09
		SlotCharacteristics_t uSlotCharacteristics; // 0x0B
		// 2.1+
		SlotCharacteristicsExtended_t uSlotCharacteristicsExtended; // 0x0C
		// 2.6+
		std::uint16_t nSegmentGroupNumber; // 0x0D
		std::uint8_t nBusNumber; // 0x0F
		struct
		{
			std::uint8_t uFunctionNumber : 3;
			std::uint8_t uDeviceNumber : 5;
		}; // 0x10
		// 3.2+
		std::uint8_t nDataBusWidth; // 0x11
		std::uint8_t nPeerGroupingCount; // 0x12
		SystemSlotsPeerGroup_t arrPeerGroups[]; // 0x13
		// 3.4+
		// @note: fields below require manual parsing
		//std::uint8_t uSlotInformation; // 0x13 + 5*N
		//std::uint8_t nSlotPhysicalWidth; // 0x14 + 5*N
		//std::uint16_t nSlotPitch; // 0x15 + 5*N
		// 3.5+
		// @note: fields below require manual parsing
		//SlotHeight_t nSlotHeight; // 0x17 + 5*N
	};

	using OnBoardDeviceType_t = std::uint8_t;
	enum EOnBoardDeviceType : std::uint8_t
	{
		ONBOARD_DEVICE_OTHER = 1U,
		ONBOARD_DEVICE_UNKNOWN,
		ONBOARD_DEVICE_VIDEO,
		ONBOARD_DEVICE_SCSI_CONTROLLER,
		ONBOARD_DEVICE_ETHERNET,
		ONBOARD_DEVICE_TOKEN_RING,
		ONBOARD_DEVICE_SOUND,
		ONBOARD_DEVICE_PATA_CONTROLLER,
		ONBOARD_DEVICE_SATA_CONTROLLER,
		ONBOARD_DEVICE_SAS_CONTROLLER,
		ONBOARD_DEVICE_WIRELESS_LAN,
		ONBOARD_DEVICE_BLUETOOTH,
		ONBOARD_DEVICE_WWAN,
		ONBOARD_DEVICE_EMMC,
		ONBOARD_DEVICE_NVME_CONTROLLER,
		ONBOARD_DEVICE_UFS_CONTROLLER
	};

	struct OnBoardDevice_t
	{
		struct
		{
			OnBoardDeviceType_t nType : 7;
			std::uint8_t bEnabled : 1;
		}; // 0x0
		StringIndex_t nDescription; // 0x1
	};

	// deprecated
	struct OnBoardDevicesInformation_t
	{
		OnBoardDevice_t arrDevices[1]; // 0x4
	};

	struct OemStrings_t
	{
		std::uint8_t nCount; // 0x4
	};

	struct SystemConfigurationOptions_t
	{
		std::uint8_t nCount; // 0x4
	};

	struct FirmwareLanguageInformation_t
	{
		// 2.0+
		std::uint8_t nInstallableLanguagesCount; // 0x04
		// 2.1+
		union
		{
			std::uint8_t uFlags; // 0x05
			struct
			{
				std::uint8_t bUseAbbreviatedFormat : 1;
				std::uint8_t uReserved : 7;
			};
		};
		// 2.0+
		std::uint8_t arrReserved[15]; // 0x06
		StringIndex_t nCurrentLanguage; // 0x15
	};

	struct GroupAssociationsItem_t
	{
		StructureType_t nType; // 0x0
		std::uint16_t uHandle; // 0x1
	};

	struct GroupAssociations_t
	{
		StringIndex_t nGroupName; // 0x4
		GroupAssociationsItem_t arrItems[]; // 0x5
	};

	using EventLogAccessMethod_t = std::uint8_t;
	enum EEventLogAccessMethod : std::uint8_t
	{
		EVENT_LOG_ACCESS_METHOD_IO_ONE_8BIT_INDEX_ONE_8BIT_DATA = 0U,
		EVENT_LOG_ACCESS_METHOD_IO_TWO_8BIT_INDEX_ONE_8BIT_DATA,
		EVENT_LOG_ACCESS_METHOD_IO_ONE_16BIT_INDEX_ONE_8BIT_DATA,
		EVENT_LOG_ACCESS_METHOD_MEMORY_MAPPED_PHYSICAL_32BIT_ADDRESS,
		EVENT_LOG_ACCESS_METHOD_GENERAL_PURPOSE_NON_VOLATILE
	};

	using EventLogType_t = std::uint8_t;
	enum EEventLogType : std::uint8_t
	{
		EVENT_LOG_SINGLE_BIT_ECC_MEMORY_ERROR = 1U,
		EVENT_LOG_MULTI_BIT_ECC_MEMORY_ERROR,
		EVENT_LOG_PARITY_MEMORY_ERROR,
		EVENT_LOG_BUS_TIMEOUT,
		EVENT_LOG_IO_CHANNEL_CHECK,
		EVENT_LOG_SOFTWARE_NMI,
		EVENT_LOG_POST_MEMORY_RESIZE,
		EVENT_LOG_POST_ERROR,
		EVENT_LOG_PCI_PARITY_ERROR,
		EVENT_LOG_PCI_SYSTEM_ERROR,
		EVENT_LOG_CPU_FAILURE,
		EVENT_LOG_EISA_FAILSAFE_TIMER_TIMEOUT,
		EVENT_LOG_CORRECTABLE_MEMORY_LOG_DISABLED,
		EVENT_LOG_DISABLED,
		EVENT_LOG_SYSTEM_LIMIT_EXCEED = 16U,
		EVENT_LOG_ASYNCHRONOUS_HARDWARE_TIMER_EXPIRED,
		EVENT_LOG_SYSTEM_CONFIGURATION_INFORMATION,
		EVENT_LOG_HARD_DISK_INFORMATION,
		EVENT_LOG_SYSTEM_RECONFIGURED,
		EVENT_LOG_UNCORRECTIBLE_CPU_COMPLEX_ERROR,
		EVENT_LOG_AREA_RESET,
		EVENT_LOG_SYSTEM_BOOT,
		EVENT_LOG_END = 0xFF
	};

	using EventLogDataFormat_t = std::uint8_t;
	enum EEventLogDataFormat : std::uint8_t
	{
		EVENT_LOG_FORMAT_NONE = 0U,
		EVENT_LOG_FORMAT_HANDLE,
		EVENT_LOG_FORMAT_MULTIPLE_EVENT,
		EVENT_LOG_FORMAT_MULTIPLE_EVENT_HANDLE,
		EVENT_LOG_FORMAT_POST_RESULTS_BITMAP,
		EVENT_LOG_FORMAT_SYSTEM_MANAGEMENT,
		EVENT_LOG_FORMAT_MULTIPLE_EVENT_SYSTEM_MANAGEMENT
	};

	struct EventLogTypeDescriptor_t
	{
		EventLogType_t nLogType; // 0x0
		EventLogDataFormat_t nVariableDataFormatType; // 0x1
	};

	struct SystemEventLog_t
	{
		std::uint16_t nAreaLength; // 0x04
		std::uint16_t uHeaderStartOffset; // 0x06
		std::uint16_t uDataStartOffset; // 0x08
		EventLogAccessMethod_t nAccessMethod; // 0x0A
		struct
		{
			std::uint8_t bAreaValid : 1;
			std::uint8_t bAreaFull : 1;
			std::uint8_t uReserved : 6;
		}; // 0x0B
		std::uint32_t uChangeToken; // 0x0C
		union
		{
			std::uint32_t uAccessMethodAddress;
			struct
			{
				std::uint16_t uIndexAddress;
				std::uint16_t uDataAddress;
			};
			std::uint16_t uHandleGPNV;
		}; // 0x10
		// 2.1+
		std::uint8_t nHeaderFormat; // 0x14
		std::uint8_t nTypeDescriptorCount; // 0x15
		std::uint8_t nTypeDescriptorLength; // 0x16
		EventLogTypeDescriptor_t arrTypeDescriptorsList[]; // 0x17
	};

	using MemoryArrayLocation_t = std::uint8_t;
	enum EMemoryArrayLocation : std::uint8_t
	{
		MEMORY_ARRAY_LOCATION_OTHER = 1U,
		MEMORY_ARRAY_LOCATION_UNKNOWN,
		MEMORY_ARRAY_LOCATION_SYSTEM_BOARD,
		MEMORY_ARRAY_LOCATION_ISA,
		MEMORY_ARRAY_LOCATION_EISA,
		MEMORY_ARRAY_LOCATION_PCI,
		MEMORY_ARRAY_LOCATION_MCA,
		MEMORY_ARRAY_LOCATION_PCMCIA,
		MEMORY_ARRAY_LOCATION_PROPRIETARY,
		MEMORY_ARRAY_LOCATION_NUBUS,
		MEMORY_ARRAY_LOCATION_PC98_C20 = 160U,
		MEMORY_ARRAY_LOCATION_PC98_C24,
		MEMORY_ARRAY_LOCATION_PC98_E,
		MEMORY_ARRAY_LOCATION_PC98_LOCAL_BUS,
		MEMORY_ARRAY_LOCATION_CXL
	};

	using MemoryArrayUse_t = std::uint8_t;
	enum EMemoryArrayUse : std::uint8_t
	{
		MEMORY_ARRAY_USE_OTHER = 1U,
		MEMORY_ARRAY_USE_UNKNOWN,
		MEMORY_ARRAY_USE_SYSTEM,
		MEMORY_ARRAY_USE_VIDEO,
		MEMORY_ARRAY_USE_FLASH,
		MEMORY_ARRAY_USE_NON_VOLATILE,
		MEMORY_ARRAY_USE_CACHE
	};

	using MemoryArrayErrorCorrectionType_t = std::uint8_t;
	enum EMemoryArrayErrorCorrectionType : std::uint8_t
	{
		MEMORY_ARRAY_ERROR_CORRECTION_OTHER = 1U,
		MEMORY_ARRAY_ERROR_CORRECTION_UNKNOWN,
		MEMORY_ARRAY_ERROR_CORRECTION_NONE,
		MEMORY_ARRAY_ERROR_CORRECTION_PARITY,
		MEMORY_ARRAY_ERROR_CORRECTION_SINGLE_BIT_ECC,
		MEMORY_ARRAY_ERROR_CORRECTION_MULTI_BIT_ECC,
		MEMORY_ARRAY_ERROR_CORRECTION_CRC
	};

	struct PhysicalMemoryArray_t
	{
		// 2.1+
		MemoryArrayLocation_t nLocation; // 0x04
		MemoryArrayUse_t nUse; // 0x05
		MemoryArrayErrorCorrectionType_t nMemoryErrorCorrection; // 0x06
		std::uint32_t uMaxCapacity; // 0x07
		std::uint16_t uMemoryErrorInformationHandle; // 0x0B
		std::uint16_t nMemoryDevicesCount; // 0x0D
		// 2.7+
		std::uint64_t ullMaxCapacityExtended; // 0x0F
	};

	using MemoryDeviceFormFactor_t = std::uint8_t;
	enum EMemoryDeviceFormFactor : std::uint8_t
	{
		MEMORY_DEVICE_FORM_FACTOR_OTHER = 1U,
		MEMORY_DEVICE_FORM_FACTOR_UNKNOWN,
		MEMORY_DEVICE_FORM_FACTOR_SIMM,
		MEMORY_DEVICE_FORM_FACTOR_SIP,
		MEMORY_DEVICE_FORM_FACTOR_CHIP,
		MEMORY_DEVICE_FORM_FACTOR_DIP,
		MEMORY_DEVICE_FORM_FACTOR_ZIP,
		MEMORY_DEVICE_FORM_FACTOR_PROPRIETARY_CARD,
		MEMORY_DEVICE_FORM_FACTOR_DIMM,
		MEMORY_DEVICE_FORM_FACTOR_TSOP,
		MEMORY_DEVICE_FORM_FACTOR_ROW_OF_CHIPS,
		MEMORY_DEVICE_FORM_FACTOR_RIMM,
		MEMORY_DEVICE_FORM_FACTOR_SODIMM,
		MEMORY_DEVICE_FORM_FACTOR_SRIMM,
		MEMORY_DEVICE_FORM_FACTOR_FBDIMM,
		MEMORY_DEVICE_FORM_FACTOR_DIE,
		MEMORY_DEVICE_FORM_FACTOR_CAMM
	};

	using MemoryDeviceType_t = std::uint8_t;
	enum EMemoryDeviceType : std::uint8_t
	{
		MEMORY_DEVICE_OTHER = 1U,
		MEMORY_DEVICE_UNKNOWN,
		MEMORY_DEVICE_DRAM,
		MEMORY_DEVICE_EDRAM,
		MEMORY_DEVICE_VRAM,
		MEMORY_DEVICE_SRAM,
		MEMORY_DEVICE_RAM,
		MEMORY_DEVICE_ROM,
		MEMORY_DEVICE_FLASH,
		MEMORY_DEVICE_EEPROM,
		MEMORY_DEVICE_FEPROM,
		MEMORY_DEVICE_EPROM,
		MEMORY_DEVICE_CDRAM,
		MEMORY_DEVICE_3DRAM,
		MEMORY_DEVICE_SDRAM,
		MEMORY_DEVICE_SGRAM,
		MEMORY_DEVICE_RDRAM,
		MEMORY_DEVICE_DDR,
		MEMORY_DEVICE_DDR2,
		MEMORY_DEVICE_DDR2_FBDIMM,
		// reserved 21-23
		MEMORY_DEVICE_DDR3 = 24U,
		MEMORY_DEVICE_FBD2,
		MEMORY_DEVICE_DDR4,
		MEMORY_DEVICE_LPDDR,
		MEMORY_DEVICE_LPDDR2,
		MEMORY_DEVICE_LPDDR3,
		MEMORY_DEVICE_LPDDR4,
		MEMORY_DEVICE_LOGICAL_NON_VOLATILE,
		MEMORY_DEVICE_HBM,
		MEMORY_DEVICE_HBM2,
		MEMORY_DEVICE_DDR5,
		MEMORY_DEVICE_LPDDR5,
		MEMORY_DEVICE_HBM3
	};

	using MemoryDeviceTypeDetail_t = std::uint16_t;
	enum EMemoryDeviceTypeDetail : std::uint16_t
	{
		MEMORY_DEVICE_TYPE_DETAIL_OTHER = 1U << 0U,
		MEMORY_DEVICE_TYPE_DETAIL_UNKNOWN = 1U << 1U,
		MEMORY_DEVICE_TYPE_DETAIL_FAST_PAGED = 1U << 2U,
		MEMORY_DEVICE_TYPE_DETAIL_STATIC_COLUMN = 1U << 3U,
		MEMORY_DEVICE_TYPE_DETAIL_PSEUDO_STATIC = 1U << 4U,
		MEMORY_DEVICE_TYPE_DETAIL_RAMBUS = 1U << 5U,
		MEMORY_DEVICE_TYPE_DETAIL_SYNCHRONOUS = 1U << 6U,
		MEMORY_DEVICE_TYPE_DETAIL_CMOS = 1U << 7U,
		MEMORY_DEVICE_TYPE_DETAIL_EDO = 1U << 8U,
		MEMORY_DEVICE_TYPE_DETAIL_WINDOW_DRAM = 1U << 9U,
		MEMORY_DEVICE_TYPE_DETAIL_CACHE_DRAM = 1U << 10U,
		MEMORY_DEVICE_TYPE_DETAIL_NON_VOLATILE = 1U << 11U,
		MEMORY_DEVICE_TYPE_DETAIL_REGISTERED = 1U << 12U,
		MEMORY_DEVICE_TYPE_DETAIL_UNREGISTERED = 1U << 13U,
		MEMORY_DEVICE_TYPE_DETAIL_LRDIMM = 1U << 14U
	};

	using MemoryTechnology_t = std::uint8_t;
	enum EMemoryTechnology : std::uint8_t
	{
		MEMORY_TECHNOLOGY_OTHER = 1U,
		MEMORY_TECHNOLOGY_UNKNOWN,
		MEMORY_TECHNOLOGY_DRAM,
		MEMORY_TECHNOLOGY_NVDIMM_N,
		MEMORY_TECHNOLOGY_NVDIMM_F,
		MEMORY_TECHNOLOGY_NVDIMM_P,
		MEMORY_TECHNOLOGY_INTEL_OPTANE,
		MEMORY_TECHNOLOGY_MRDIMM
	};

	using MemoryOperatingModeCapability_t = std::uint16_t;
	enum EMemoryOperatingModeCapability : std::uint16_t
	{
		MEMORY_OPERATING_MODE_OTHER = 1U << 0U,
		MEMORY_OPERATING_MODE_UNKNOWN = 1U << 1U,
		MEMORY_OPERATING_MODE_VOLATILE = 1U << 2U,
		MEMORY_OPERATING_MODE_BYTE_ACCESSIBLE_PERSISTENT = 1U << 3U,
		MEMORY_OPERATING_MODE_BLOCK_ACCESSIBLE_PERSISTENT = 1U << 4U
	};

	struct MemoryDevice_t
	{
		// 2.1+
		std::uint16_t uPhysicalMemoryArrayHandle; // 0x04
		std::uint16_t uMemoryErrorInformationHandle; // 0x06
		std::uint16_t nTotalWidth; // 0x08
		std::uint16_t nDataWidth; // 0x0A
		struct
		{
			std::uint16_t nSize : 15;
			std::uint16_t nSizeGranulatiry : 1;
		}; // 0x0C
		MemoryDeviceFormFactor_t nFormFactor; // 0x0E
		std::uint8_t uDeviceSet; // 0x0F
		StringIndex_t nDeviceLocator; // 0x10
		StringIndex_t nBankLocator; // 0x11
		MemoryDeviceType_t nMemoryType; // 0x12
		MemoryDeviceTypeDetail_t uTypeDetail; // 0x13
		// 2.3+
		std::uint16_t uSpeed; // 0x15
		StringIndex_t nManufacturer; // 0x17
		StringIndex_t nSerialNumber; // 0x18
		StringIndex_t nAssetTag; // 0x19
		StringIndex_t nPartNumber; // 0x1A
		// 2.6+
		union
		{
			std::uint8_t uAttributes;
			struct
			{
				std::uint8_t uRank : 4;
				std::uint8_t uReserved0 : 4;
			};
		}; // 0x1B
		// 2.7+
		struct
		{
			std::uint32_t nSizeExtended : 31;
			std::uint32_t nSizeExtendedGranulatiry : 1;
		}; // 0x1C
		std::uint16_t uConfiguredSpeed; // 0x20
		// 2.8+
		std::uint16_t uMinVoltage; // 0x22
		std::uint16_t uMaxVoltage; // 0x24
		std::uint16_t uConfiguredVoltage; // 0x26
		// 3.2+
		MemoryTechnology_t nMemoryTechnology; // 0x28
		MemoryOperatingModeCapability_t uOperatingModeCapability; // 0x29
		StringIndex_t nFirmwareVersion; // 0x2B
		std::uint16_t uModuleManufacturerID; // 0x2C
		std::uint16_t uModuleProductID; // 0x2E
		std::uint16_t uMemorySubsystemControllerManufacturerID; // 0x30
		std::uint16_t uMemorySubsystemControllerProductID; // 0x32
		std::uint64_t ullNonVolatileSize; // 0x34
		std::uint64_t ullVolatileSize; // 0x3C
		std::uint64_t ullCacheSize; // 0x44
		std::uint64_t ullLogicalSize; // 0x4C
		// 3.3+
		struct
		{
			std::uint32_t uSpeedExtended : 31;
			std::uint32_t uReserved1 : 1; 
		}; // 0x54
		struct
		{
			std::uint32_t uConfiguredSpeedExtended : 31;
			std::uint32_t uReserved2 : 1;
		}; // 0x58
		// 3.7+
		std::uint16_t uPMIC0ManufacturerID; // 0x5C
		std::uint16_t uPMIC0RevisionNumber; // 0x5E
		std::uint16_t uRCDManufacturerID; // 0x60
		std::uint16_t uRCDRevisionNumber; // 0x62
	};

	using MemoryErrorType_t = std::uint8_t;
	enum EMemoryErrorType : std::uint8_t
	{
		MEMORY_ERROR_OTHER = 1U,
		MEMORY_ERROR_UNKNOWN,
		MEMORY_ERROR_OK,
		MEMORY_ERROR_BAD_READ,
		MEMORY_ERROR_PARITY,
		MEMORY_ERROR_SINGLE_BIT,
		MEMORY_ERROR_DOUBLE_BIT,
		MEMORY_ERROR_MULTI_BIT,
		MEMORY_ERROR_NIBBLE,
		MEMORY_ERROR_CHECKSUM,
		MEMORY_ERROR_CRC,
		MEMORY_ERROR_CORRECTED_SINGLE_BIT,
		MEMORY_ERROR_CORRECTED,
		MEMORY_ERROR_UNCORRECTLABLE
	};

	using MemoryErrorGranularity_t = std::uint8_t;
	enum EMemoryErrorGranularity : std::uint8_t
	{
		MEMORY_ERROR_GRANULATIRY_OTHER = 1U,
		MEMORY_ERROR_GRANULATIRY_UNKNOWN,
		MEMORY_ERROR_GRANULATIRY_DEVICE_LEVEL,
		MEMORY_ERROR_GRANULATIRY_PARTITION_LEVEL
	};

	using MemoryErrorOperation_t = std::uint8_t;
	enum EMemoryErrorOperation : std::uint8_t
	{
		MEMORY_ERROR_OPERATION_OTHER = 1U,
		MEMORY_ERROR_OPERATION_UNKNOWN,
		MEMORY_ERROR_OPERATION_READ,
		MEMORY_ERROR_OPERATION_WRITE,
		MEMORY_ERROR_OPERATION_PARTIAL_WRITE
	};

	struct Memory32ErrorInformation_t
	{
		// 2.1+
		MemoryErrorType_t nType; // 0x04
		MemoryErrorGranularity_t nGranularity; // 0x05
		MemoryErrorOperation_t nOperation; // 0x06
		std::uint32_t uVendorSyndrome; // 0x07
		std::uint32_t uArrayErrorAddress; // 0x0B
		std::uint32_t uDeviceErrorAddress; // 0x0F
		std::uint32_t uResolution; // 0x13
	};

	struct MemoryArrayMappedAddress_t
	{
		// 2.1+
		std::uint32_t uStartingAddress; // 0x04
		std::uint32_t uEndingAddress; // 0x08
		std::uint16_t uArrayHandle; // 0x0C
		std::uint8_t nPartitionWidth; // 0x0E
		// 2.7+
		std::uint64_t ullStartingAddressExtended; // 0x0F
		std::uint64_t ullEndingAddressExtended; // 0x17
	};

	struct MemoryDeviceMappedAddress_t
	{
		// 2.1+
		std::uint32_t uStartingAddress; // 0x04
		std::uint32_t uEndingAddress; // 0x08
		std::uint16_t uDeviceHandle; // 0x0C
		std::uint16_t uArrayMappedAddressHandle; // 0x0E
		std::uint8_t uPartitionRowPosition; // 0x10
		std::uint8_t uInterleavePosition; // 0x11
		std::uint8_t uInterleaveDataDepth; // 0x12
		// 2.7+
		std::uint64_t ullStartingAddressExtended; // 0x13
		std::uint64_t ullEndingAddressExtended; // 0x1B
	};

	using PointingDeviceType_t = std::uint8_t;
	enum EPointingDeviceType : std::uint8_t
	{
		POINTING_DEVICE_OTHER = 1U,
		POINTING_DEVICE_UNKNOWN,
		POINTING_DEVICE_MOUSE,
		POINTING_DEVICE_TRACK_BALL,
		POINTING_DEVICE_TRACK_POINT,
		POINTING_DEVICE_GLIDE_POINT,
		POINTING_DEVICE_TOUCH_PAD,
		POINTING_DEVICE_TOUCH_SCREEN,
		POINTING_DEVICE_OPTICAL_SENSOR
	};

	using PointingDeviceInterface_t = std::uint8_t;
	enum EPointingDeviceInterface : std::uint8_t
	{
		POINTING_DEVICE_INTERFACE_OTHER = 1U,
		POINTING_DEVICE_INTERFACE_UNKNOWN,
		POINTING_DEVICE_INTERFACE_SERIAL,
		POINTING_DEVICE_INTERFACE_PS2,
		POINTING_DEVICE_INTERFACE_INFRARED,
		POINTING_DEVICE_INTERFACE_HP_HIL,
		POINTING_DEVICE_INTERFACE_BUS_MOUSE,
		POINTING_DEVICE_INTERFACE_ADB,
		POINTING_DEVICE_INTERFACE_BUS_MOUSE_DB9 = 160U,
		POINTING_DEVICE_INTERFACE_BUS_MOUSE_MICRO_DIN,
		POINTING_DEVICE_INTERFACE_USB,
		POINTING_DEVICE_INTERFACE_I2C,
		POINTING_DEVICE_INTERFACE_SPI
	};

	struct BuiltinPointingDevice_t
	{
		// 2.1+
		PointingDeviceType_t nType; // 0x4
		PointingDeviceInterface_t nInterface; // 0x5
		std::uint8_t nButtonsCount; // 0x6
	};

	using PortableBatteryChemistry_t = std::uint8_t;
	enum EPortableBatteryChemistry : std::uint8_t
	{
		PORTABLE_BATTERY_CHEMISTRY_OTHER = 1U,
		PORTABLE_BATTERY_CHEMISTRY_UNKNOWN,
		PORTABLE_BATTERY_CHEMISTRY_LEAD_ACID,
		PORTABLE_BATTERY_CHEMISTRY_NICKEL_CADMIUM,
		PORTABLE_BATTERY_CHEMISTRY_NICKEL_METAL_HYDRIDE,
		PORTABLE_BATTERY_CHEMISTRY_LITHIUM_ION,
		PORTABLE_BATTERY_CHEMISTRY_ZINC_AIR,
		PORTABLE_BATTERY_CHEMISTRY_LITHIUM_POLYMER
	};

	struct PortableBattery_t
	{
		// 2.1+
		StringIndex_t nLocation; // 0x04
		StringIndex_t nManufacturer; // 0x05
		StringIndex_t nManufactureDate; // 0x06
		StringIndex_t nSerialNumber; // 0x07
		StringIndex_t nDeviceName; // 0x08
		PortableBatteryChemistry_t nDeviceChemistry; // 0x09
		std::uint16_t uDesignCapacity; // 0x0A
		std::uint16_t uDesignVoltage; // 0x0C
		StringIndex_t nVersionNumberSBDS; // 0x0E
		std::uint8_t uMaxDataError; // 0x0F
		// 2.2+
		std::uint16_t uSerialNumberSBDS; // 0x10
		struct
		{
			std::uint16_t nManufactureDaySBDS : 5;
			std::uint16_t nManufactureMonthSBDS : 4;
			std::uint16_t nManufactureYearSBDS : 7;
		}; // 0x12
		StringIndex_t nDeviceChemistrySBDS; // 0x14
		std::uint8_t uDesignCapacityMultiplier; // 0x15
		std::uint32_t uOemSpecific; // 0x16
	};

	struct SystemReset_t
	{
		union
		{
			std::uint8_t uCapabilities;
			struct
			{
				std::uint8_t bStatus : 1;
				std::uint8_t nBootOption : 2;
				std::uint8_t nBootOptionOnLimit : 2;
				std::uint8_t bWatchdogTimer : 1;
				std::uint8_t uReserved : 2;
			};
		}; // 0x4
		std::uint16_t nResetCount; // 0x5
		std::uint16_t nResetLimit; // 0x7
		std::uint16_t uTimerInterval; // 0x9
		std::uint16_t uTimeout; // 0xB
	};

	using HardwareSecurityStatus_t = std::uint8_t;
	enum EHardwareSecurityStatus_t : std::uint8_t
	{
		HARDWARE_SECURITY_DISABLED = 0U,
		HARDWARE_SECURITY_ENABLED,
		HARDWARE_SECURITY_NOT_IMPLEMENTED,
		HARDWARE_SECURITY_UNKNOWN
	};

	struct HardwareSecurity_t
	{
		union
		{
			std::uint8_t uSettings;
			struct
			{
				HardwareSecurityStatus_t nFrontPanelResetStatus : 2;
				HardwareSecurityStatus_t nAdministratorPasswordStatus : 2;
				HardwareSecurityStatus_t nKeyboardPasswordStatus : 2;
				HardwareSecurityStatus_t nPowerOnPasswordStatus : 2;
			};
		}; // 0x4
	};

	struct SystemPowerControls_t
	{
		std::uint8_t uNextPowerOnMonth; // 0x4
		std::uint8_t uNextPowerOnDay; // 0x5
		std::uint8_t uNextPowerOnHour; // 0x6
		std::uint8_t uNextPowerOnMinute; // 0x7
		std::uint8_t uNextPowerOnSecond; // 0x8
	};

	struct VoltageProbe_t
	{
		StringIndex_t nDescription; // 0x04
		struct
		{
			ProbeLocation_t nLocation : 5;
			Status_t nStatus : 3;
		}; // 0x05
		std::uint16_t uMaxValue; // 0x06
		std::uint16_t uMinValue; // 0x08
		std::uint16_t uResolution; // 0x0A
		std::uint16_t uTolerance; // 0x0C
		std::uint16_t uAccuracy; // 0x0E
		std::uint32_t uOemDefined; // 0x10
		std::uint16_t uNominalValue; // 0x14
	};

	using CoolingDeviceType_t = std::uint8_t;
	enum ECoolingDeviceType : std::uint8_t
	{
		COOLING_DEVICE_OTHER = 1U,
		COOLING_DEVICE_UNKNOWN,
		COOLING_DEVICE_FAN,
		COOLING_DEVICE_CENTRIFUGAL_BLOWER,
		COOLING_DEVICE_CHIP_FAN,
		COOLING_DEVICE_CABINET_FAN,
		COOLING_DEVICE_POWER_SUPPLY_FAN,
		COOLING_DEVICE_HEAT_PIPE,
		COOLING_DEVICE_INTEGRATED_REFRIGERATION,
		COOLING_DEVICE_ACTIVE_COOLING = 16U,
		COOLING_DEVICE_PASSIVE_COOLING
	};

	struct CoolingDevice_t
	{
		// 2.2+
		std::uint16_t uTemperatureProbeHandle; // 0x4
		struct
		{
			CoolingDeviceType_t nType : 5;
			Status_t nStatus : 3;
		}; // 0x6
		std::uint8_t uCoolingUnitGroup; // 0x7
		std::uint32_t uOemDefined; // 0x8
		std::uint16_t uNominalSpeed; // 0xC
		// 2.7+
		StringIndex_t nDescription; // 0xE
	};

	struct TemperatureProbe_t
	{
		// 2.2+
		StringIndex_t nDescription; // 0x4
		struct
		{
			ProbeLocation_t nLocation : 5;
			Status_t nStatus : 3;
		}; // 0x5
		std::uint16_t uMaxValue; // 0x6
		std::uint16_t uMinValue; // 0x8
		std::uint16_t uResolution; // 0xA
		std::uint16_t uTolerance; // 0xC
		std::uint16_t uAccuracy; // 0xE
		std::uint32_t uOemDefined; // 0x10
		std::uint16_t uNominalValue; // 0x14
	};

	struct ElectricalCurrentProbe_t
	{
		StringIndex_t nDescription; // 0x4
		struct
		{
			ProbeLocation_t nLocation : 5;
			Status_t nStatus : 3;
		}; // 0x5
		std::uint16_t uMaxValue; // 0x6
		std::uint16_t uMinValue; // 0x8
		std::uint16_t uResolution; // 0xA
		std::uint16_t uTolerance; // 0xC
		std::uint16_t uAccuracy; // 0xE
		std::uint32_t uOemDefined; // 0x10
		std::uint16_t uNominalValue; // 0x14
	};

	struct OutOfBandRemoteAccess_t
	{
		StringIndex_t nManufacturer; // 0x4
		union
		{
			std::uint8_t uConnections;
			struct
			{
				std::uint8_t bInboundConnection : 1;
				std::uint8_t bOutboundConnection : 1;
				std::uint8_t uReserved : 6;
			};
		}; // 0x5
	};

	struct BootIntegrityServicesEntryPoint_t
	{
		// 2.3+
	};

	using BootStatus_t = std::uint8_t;
	enum EBootStatus : std::uint8_t
	{
		BOOT_STATUS_NO_ERROR = 0U,
		BOOT_STATUS_NO_BOOTABLE_MEDIA,
		BOOT_STATUS_OPERATING_SYSTEM_FAILED_TO_LOAD,
		BOOT_STATUS_FIRMWARE_DETECTED_HARDWARE_FAILURE,
		BOOT_STATUS_OPERATING_SYSTEM_DETECTED_HARDWARE_FAILURE,
		BOOT_STATUS_USER_REQUESTED,
		BOOT_STATUS_SYSTEM_SECURITY_VIOLATION,
		BOOT_STATUS_PREVIOUSLY_REQUESTED_IMAGE,
		BOOT_STATUS_SYSTEM_WATCHDOG_EXPIRED
	};

	struct SystemBootInformation_t
	{
		// 2.3+
		std::uint8_t arrReserved[6]; // 0x4
		BootStatus_t nBootStatus; // 0xA
		std::uint8_t arrAdditionalData[9]; // 0xB
	};

	struct Memory64ErrorInformation_t
	{
		// 2.3+
		MemoryErrorType_t nType; // 0x04
		MemoryErrorType_t nGranularity; // 0x05
		MemoryErrorType_t nOperation; // 0x06
		std::uint32_t uVendorSyndrome; // 0x07
		std::uint64_t ullArrayErrorAddress; // 0x0B
		std::uint64_t ullDeviceErrorAddress; // 0x13
		std::uint32_t uResolution; // 0x1B
	};

	using ManagementDeviceType_t = std::uint8_t;
	enum EManagementDeviceType : std::uint8_t
	{
		MANAGEMENT_DEVICE_OTHER = 1U,
		MANAGEMENT_DEVICE_UNKNOWN,
		MANAGEMENT_DEVICE_LM75,
		MANAGEMENT_DEVICE_LM78,
		MANAGEMENT_DEVICE_LM79,
		MANAGEMENT_DEVICE_LM80,
		MANAGEMENT_DEVICE_LM81,
		MANAGEMENT_DEVICE_ADM9240,
		MANAGEMENT_DEVICE_DS1780,
		MANAGEMENT_DEVICE_MAX1617,
		MANAGEMENT_DEVICE_GL518SM,
		MANAGEMENT_DEVICE_W83781D,
		MANAGEMENT_DEVICE_HT82H791
	};

	using ManagementDeviceAddressType_t = std::uint8_t;
	enum EManagementDeviceAddressType : std::uint8_t
	{
		MANAGEMENT_DEVICE_ADDRESS_OTHER = 1U,
		MANAGEMENT_DEVICE_ADDRESS_UNKNOWN,
		MANAGEMENT_DEVICE_ADDRESS_IO_PORT,
		MANAGEMENT_DEVICE_ADDRESS_MEMORY,
		MANAGEMENT_DEVICE_ADDRESS_SMBUS
	};

	struct ManagementDevice_t
	{
		// 2.3+
		StringIndex_t nDescription; // 0x4
		ManagementDeviceType_t nType; // 0x5
		std::uint32_t uAddress; // 0x6
		ManagementDeviceAddressType_t nAddressType; // 0xA
	};

	struct ManagementDeviceComponent_t
	{
		// 2.3+
		StringIndex_t nDescription; // 0x4
		std::uint16_t uDeviceHandle; // 0x5
		std::uint16_t uComponentHandle; // 0x7
		std::uint16_t uThresholdHandle; // 0x9
	};

	struct ManagementDeviceThresholdData_t
	{
		// 2.3+
		std::uint16_t uLowerNonCritical; // 0x4
		std::uint16_t uUpperNonCritical; // 0x6
		std::uint16_t uLowerCritical; // 0x8
		std::uint16_t uUpperCritical; // 0xA
		std::uint16_t uLowerNonRecoverable; // 0xC
		std::uint16_t uUpperNonRecoverable; // 0xE
	};

	using MemoryChannelType_t = std::uint8_t;
	enum EMemoryChannelType : std::uint8_t
	{
		MEMORY_CHANNEL_OTHER = 1U,
		MEMORY_CHANNEL_UNKNOWN,
		MEMORY_CHANNEL_RAMBUS,
		MEMORY_CHANNEL_SYNCLINK
	};

	struct MemoryChannelDevice_t
	{
		std::uint8_t uLoad; // 0x0
		std::uint16_t uHandle; // 0x1
	};

	struct MemoryChannel_t
	{
		// 2.3+
		MemoryChannelType_t nType; // 0x4
		std::uint8_t uMaxLoad; // 0x5
		std::uint8_t nDeviceCount; // 0x6
		MemoryChannelDevice_t arrDevices[]; // 0x7
	};

	using BMCInterfaceType_t = std::uint8_t;
	enum EBMCInterfaceType : std::uint8_t
	{
		BMC_INTERFACE_UNKNOWN = 0U,
		BMC_INTERFACE_KCS,
		BMC_INTERFACE_SMIC,
		BMC_INTERFACE_BT,
		BMC_INTERFACE_SSIF
	};

	struct IPMIDeviceInformation_t
	{
		BMCInterfaceType_t nInterfaceType; // 0x04
		std::uint8_t uSpecificationRevision; // 0x05
		std::uint8_t uTargetAddressI2C; // 0x06
		std::uint8_t uStorageDeviceAddressNV; // 0x06
		struct
		{
			std::uint64_t bBaseAddressIoSpace : 1;
			std::uint64_t ullBaseAddress : 63;
		}; // 0x08
		struct
		{
			union
			{
				std::uint8_t uInterruptInfo : 4;
				struct
				{
					std::uint8_t nInterruptTriggerMode : 1;
					std::uint8_t nInterruptPolarity : 1;
					std::uint8_t uReserved0 : 1;
					std::uint8_t bInterruptInfoSpecified : 1;
				};
			};
			union
			{
				std::uint8_t uBaseAddressModifier : 4;
				struct
				{
					std::uint8_t uBaseAddressLSB : 1;
					std::uint8_t uReserved1 : 1;
					std::uint8_t nBaseAddressRegisterSpacing : 2;
				};
			};
		}; // 0x10
		std::uint8_t uInterruptNumber; // 0x11
	};
	
	using PowerSupplyInputVoltageRangeSwitching_t = std::uint16_t;
	enum EPowerSupplyInputVoltageRangeSwitching : std::uint8_t
	{
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_OTHER = 1U,
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_UNKNOWN,
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_MANUAL,
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_AUTO,
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_WIDE,
		POWER_SUPPLY_INPUT_VOLTAGE_RANGE_SWITCHING_NOT_APPLICABLE
	};

	using PowerSupplyStatus_t = std::uint16_t;

	using PowerSupplyType_t = std::uint16_t;
	enum EPowerSupplyType : std::uint8_t
	{
		POWER_SUPPLY_OTHER = 1U,
		POWER_SUPPLY_UNKNOWN,
		POWER_SUPPLY_LINEAR,
		POWER_SUPPLY_SWITCHING,
		POWER_SUPPLY_BATTERY,
		POWER_SUPPLY_UPS,
		POWER_SUPPLY_CONVERTER,
		POWER_SUPPLY_REGULATOR
	};

	struct SystemPowerSupply_t
	{
		// 2.3.1+
		std::uint8_t uPowerUnitGroup; // 0x04
		StringIndex_t nLocation; // 0x05
		StringIndex_t nDeviceName; // 0x06
		StringIndex_t nManufacturer; // 0x07
		StringIndex_t nSerialNumber; // 0x08
		StringIndex_t nAssetTagNumber; // 0x09
		StringIndex_t nModelPartNumber; // 0x0A
		StringIndex_t nRevisionLevel; // 0x0B
		std::uint16_t uMaxPowerCapacity; // 0x0C
		union
		{
			std::uint16_t uCharacteristics; 
			struct
			{
				std::uint16_t bHotReplaceable : 1;
				std::uint16_t bIsPresent : 1;
				std::uint16_t bUnplugged : 1;
				PowerSupplyInputVoltageRangeSwitching_t uInputVoltageRangeSwitching : 4;
				PowerSupplyStatus_t nStatus : 3;
				PowerSupplyType_t nType : 4;
				std::uint16_t uReserved : 2;
			};
		}; // 0x0E
		std::uint16_t uInputVoltageProbeHandle; // 0x10
		std::uint16_t uCoolingDeviceHandle; // 0x12
		std::uint16_t uInputCurrentProbeHandle; // 0x14
	};

	struct AdditionalInformationEntry_t
	{
		std::uint8_t nLength; // 0x0
		std::uint16_t uReferencedHandle; // 0x1
		std::uint8_t uReferencedOffset; // 0x3
		StringIndex_t nString; // 0x4
		// @note: fields below require manual parsing
		//std::uint8_t arrValue[]; // 0x5
	};

	struct AdditionalInformation_t
	{
		// 2.6+
		std::uint8_t nEntriesCount; // 0x4
		AdditionalInformationEntry_t arrEntries[]; // 0x4
	};

	struct OnBoardDevicesExtendedInformation_t
	{
		// 2.6+
		StringIndex_t nReferenceDesignation; // 0x4
		struct
		{
			OnBoardDeviceType_t nType : 7;
			std::uint8_t bEnabled : 1;
		}; // 0x5
		std::uint8_t uTypeInstance; // 0x6
		std::uint16_t uSegmentGroupNumber; // 0x7
		std::uint8_t uBusNumber; // 0x9
		struct
		{
			std::uint8_t uFunctionNumber : 3;
			std::uint8_t uDeviceNumber : 5;
		}; // 0xA
	};

	/*
	 * based on DMTF-DSP0239 (MCTP)
	 * @credits: https://www.dmtf.org/dsp/DSP0239
	 */
	using HostInterfaceType_t = std::uint8_t;
	enum EHostInterfaceType : std::uint8_t
	{
		HOST_INTERFACE_KCS = 2U,
		HOST_INTERFACE_UART_8250,
		HOST_INTERFACE_UART_16450,
		HOST_INTERFACE_UART_16550,
		HOST_INTERFACE_UART_16650,
		HOST_INTERFACE_UART_16750,
		HOST_INTERFACE_UART_16850,
		HOST_INTERFACE_I2C_SMBUS,
		HOST_INTERFACE_I3C,
		HOST_INTERFACE_PCIE_VDM,
		HOST_INTERFACE_MMBI,
		HOST_INTERFACE_PPC,
		HOST_INTERFACE_UCIE,
		HOST_INTERFACE_USB,
		HOST_INTERFACE_NETWORK = 64U
	};

	using HostInterfaceProtocolType_t = std::uint8_t;
	enum EHostInterfaceProtocolType : std::uint8_t
	{
		HOST_INTERFACE_PROTOCOL_IPMI = 2U,
		HOST_INTERFACE_PROTOCOL_MCTP,
		HOST_INTERFACE_PROTOCOL_REDFISH,
		HOST_INTERFACE_PROTOCOL_OEM_DEFINED = 240U
	};

	struct ProtocolRecordData_t
	{
		HostInterfaceProtocolType_t nType; // 0x0
		std::uint8_t nTypeSpecificDataLength; // 0x1
		std::uint8_t arrTypeSpecificData[]; // 0x2
	};

	struct ManagementControllerHostInterface_t
	{
		HostInterfaceType_t nType; // 0x4
		std::uint8_t nTypeSpecificDataLength; // 0x5
		std::uint8_t arrTypeSpecificData[]; // 0x6
		// @note: fields below require manual parsing
		//std::uint8_t nProtocolRecordCount; // 0x6 + N
		//ProtocolRecordData_t arrProtocolRecords[]; // 0x7 + N
	};

	struct TPMDevice_t
	{
		std::uint8_t arrVendorID[4]; // 0x04
		std::uint8_t uVersionMajor; // 0x08
		std::uint8_t uVersionMinor; // 0x09
		std::uint32_t uFirmwareVersionHigh; // 0x0A
		std::uint32_t uFirmwareVersionLow; // 0x0E
		StringIndex_t nDescription; // 0x12
		union
		{
			std::uint64_t ullCharacteristics;
			struct
			{
				std::uint64_t uReserved0 : 2;
				std::uint64_t bCharacteristicsNotSupported : 1;
				std::uint64_t bFamilyConfigurableViaFirmwareUpdate : 1;
				std::uint64_t bFamilyConfigurableViaPlatformSoftwareSupport : 1;
				std::uint64_t bFamilyConfigurableViaOemProprietaryMechanism : 1;
				std::uint64_t uReserved1 : 58;
			};
		}; // 0x13
		std::uint32_t uOemDefined; // 0x1B
	};

	using ProcessorArchitectureType_t = std::uint8_t;
	enum EProcessorArchitectureType : std::uint8_t
	{
		PROCESSOR_ARCHITECTURE_IA32 = 1U,
		PROCESSOR_ARCHITECTURE_X64,
		PROCESSOR_ARCHITECTURE_INTEL_ITANIUM,
		PROCESSOR_ARCHITECTURE_AARCH32,
		PROCESSOR_ARCHITECTURE_AARCH64,
		PROCESSOR_ARCHITECTURE_RV32,
		PROCESSOR_ARCHITECTURE_RV64,
		PROCESSOR_ARCHITECTURE_RV128,
		PROCESSOR_ARCHITECTURE_LOONGARCH32,
		PROCESSOR_ARCHITECTURE_LOONGARCH64
	};

	struct ProcessorSpecificBlock_t
	{
		std::uint8_t nDataLength; // 0x0
		ProcessorArchitectureType_t nArchitectureType; // 0x1
		// @note: fields below require manual parsing
		//std::uint8_t arrSpecificData[]; // 0x2
	};

	struct ProcessorAdditionalInformation_t
	{
		std::uint16_t uReferencedHandle; // 0x4
		ProcessorSpecificBlock_t arrBlocks[]; // 0x6
	};

	using FirmwareInventoryState_t = std::uint8_t;
	enum EFirmwareInventoryState : std::uint8_t
	{
		FIRMWARE_INVENTORY_STATE_OTHER = 1U,
		FIRMWARE_INVENTORY_STATE_UNKNOWN,
		FIRMWARE_INVENTORY_STATE_DISABLED,
		FIRMWARE_INVENTORY_STATE_ENABLED,
		FIRMWARE_INVENTORY_STATE_ABSENT,
		FIRMWARE_INVENTORY_STATE_STANDBY_OFFLINE,
		FIRMWARE_INVENTORY_STATE_STANDBY_SPARE,
		FIRMWARE_INVENTORY_STATE_UNAVAILABLE_OFFLINE
	};

	struct FirmwareInventoryInformation_t
	{
		// 3.5+
		StringIndex_t nFirmwareComponentName; // 0x04
		StringIndex_t nFirmwareVersion; // 0x05
		std::uint8_t nFirmwareVersionFormat; // 0x06 // @todo: enum?
		StringIndex_t nFirmwareID; // 0x07
		std::uint8_t nFirmwareIDFormat; // 0x08 // @todo: enum?
		StringIndex_t nReleaseDate; // 0x09
		StringIndex_t nManufacturer; // 0x0A
		StringIndex_t nLowestSupportedFirmwareVersion; // 0x0B
		std::uint64_t ullImageSize; // 0x0C
		union
		{
			std::uint16_t uCharacteristics;
			struct
			{
				std::uint16_t bUpdateable : 1;
				std::uint16_t bWriteProtect : 1;
				std::uint16_t uReserved : 14;
			};
		}; // 0x14
		FirmwareInventoryState_t nState; // 0x16
		std::uint8_t nAssociatedComponentCount; // 0x17
		std::uint16_t arrAssociatedComponentHandles[]; // 0x18
	};

	struct StringProperty_t
	{
		// 3.5+
		std::uint16_t uIdentifier; // 0x4
		StringIndex_t nValue; // 0x6
		std::uint16_t uParentHandle; // 0x7
	};
#pragma pack(pop)
#ifdef Q_COMPILER_MSC
#pragma warning(pop)
#endif

	/// read the given structure table
	/// @param[in] pCurrentStructure pointer to the current (or initial) structure in the table
	/// @param[out] pszStringMap [optional] map of the current structure strings
	/// @param[out] pnStringCount [optional] count of the structure strings
	/// @returns: pointer to the next structure if there's any, null otherwise
	inline StructureHeader_t* ReadStructure(const StructureHeader_t* pCurrentStructure, const char** pszStringMap = nullptr, std::size_t* pnStringCount = nullptr)
	{
		if (pCurrentStructure == nullptr)
			return nullptr;

		// zero out first entry of the string map
		if (pszStringMap != nullptr)
			*pszStringMap = nullptr;

		// check for special type indicating it's last table entry
		if (pCurrentStructure->nType == TYPE_END_OF_TABLE)
		{
			if (pnStringCount != nullptr)
				*pnStringCount = 0U;

			return nullptr;
		}

		const std::uint8_t* pCurrentStructureEnd = reinterpret_cast<const std::uint8_t*>(pCurrentStructure);
		pCurrentStructureEnd += pCurrentStructure->nLength;

		// check for the end of the structure (double terminating null)
		std::size_t nStringCount = 0U;
		if (pCurrentStructureEnd[0] == 0U && pCurrentStructureEnd[1] == 0U)
			pCurrentStructureEnd += 2U;
		// otherwise look for the string map
		else
		{
			while (true)
			{
				++nStringCount;

				if (pszStringMap != nullptr)
					pszStringMap[nStringCount] = reinterpret_cast<const char*>(pCurrentStructureEnd);

				// look for the end of the current string
				while (*pCurrentStructureEnd++ != '\0');

				// check for double terminating null
				if (*pCurrentStructureEnd == 0U)
				{
					++pCurrentStructureEnd;
					break;
				}
			}
		}

		if (pnStringCount != nullptr)
			*pnStringCount = nStringCount;

		return reinterpret_cast<StructureHeader_t*>(const_cast<std::uint8_t*>(pCurrentStructureEnd));
	}
}
